# Generated by Django 5.2.8 on 2025-11-17 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supplier_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initial", models.CharField(null=True)),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("", "Не включать"),
                            ("article", "Артикул поставщика"),
                            ("name", "Название"),
                            ("category", "Категория"),
                            ("discounts", "Группа скидок"),
                            ("manufacturer", "Производитель"),
                            ("stock", "Остаток"),
                            ("supplier_price", "Цена поставщика в валюте поставщика"),
                            ("rrp", "РРЦ в валюте поставщика"),
                        ]
                    ),
                ),
                ("value", models.CharField()),
            ],
            options={
                "verbose_name": "Связка",
                "verbose_name_plural": "Связки",
            },
        ),
        migrations.CreateModel(
            name="Dict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(verbose_name="Если")),
                ("value", models.CharField(verbose_name="То")),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setting_manager.link",
                        verbose_name="Столбец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Словарь",
                "verbose_name_plural": "Словари",
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название")),
                ("sheet_name", models.CharField(verbose_name="Название листа")),
                (
                    "priced_only",
                    models.BooleanField(
                        default=True, verbose_name="Не включать поля без цены"
                    ),
                ),
                (
                    "update_main",
                    models.BooleanField(
                        default=True, verbose_name="Обновлять главный прайс"
                    ),
                ),
                (
                    "differ_by_name",
                    models.BooleanField(
                        default=True, verbose_name="Различать по имени"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="supplier_manager.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка",
                "verbose_name_plural": "Настройки",
            },
        ),
        migrations.AddField(
            model_name="link",
            name="setting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="setting_manager.setting",
            ),
        ),
        migrations.AddConstraint(
            model_name="setting",
            constraint=models.UniqueConstraint(
                fields=("name", "supplier"), name="name_supplier_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="link",
            constraint=models.UniqueConstraint(
                fields=("setting", "key"), name="product-field-constraint"
            ),
        ),
    ]
