# Generated by Django 5.2.5 on 2025-12-01 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0045_remove_link_setting_remove_setting_supplier_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Link',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('initial', models.CharField(null=True)),
                        ('key', models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('category', 'Категория'), ('discounts', 'Группа скидок'), ('manufacturer', 'Производитель'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('rrp', 'РРЦ в валюте поставщика')])),
                        ('value', models.CharField()),
                    ],
                ),
            ],
            # Table already exists. See core\migrations\0045_remove_link_setting_remove_setting_supplier_and_more.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Dict',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('key', models.CharField(verbose_name='Если')),
                        ('value', models.CharField(verbose_name='То')),
                        ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier_product_manager.link', verbose_name='Столбец')),
                    ],
                ),
            ],
            # Table already exists. See core\migrations\0045_remove_link_setting_remove_setting_supplier_and_more.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Setting',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(verbose_name='Название')),
                        ('sheet_name', models.CharField(verbose_name='Название листа')),
                        ('priced_only', models.BooleanField(default=True, verbose_name='Не включать поля без цены')),
                        ('update_main', models.BooleanField(default=True, verbose_name='Обновлять главный прайс')),
                        ('differ_by_name', models.BooleanField(default=True, verbose_name='Различать по имени')),
                        ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
                    ],
                ),
            ],
            # Table already exists. See core\migrations\0045_remove_link_setting_remove_setting_supplier_and_more.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='link',
                    name='setting',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_product_manager.setting'),
                ),
            ],
            # Table already exists. See core\migrations\0045_remove_link_setting_remove_setting_supplier_and_more.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SupplierProduct',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('article', models.CharField(verbose_name='Артикул поставщика')),
                        ('name', models.CharField(verbose_name='Название')),
                        ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                        ('supplier_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена поставщика в валюте поставщика')),
                        ('rrp', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РРЦ в валюте поставщика')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                        ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория')),
                        ('discounts', models.ManyToManyField(related_name='products', to='core.discount', verbose_name='Группа скидок')),
                        ('main_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_product', to='core.mainproduct', verbose_name='sku')),
                        ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_product', to='core.manufacturer', verbose_name='Производитель')),
                        ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_product', to='core.supplier', verbose_name='Поставщик')),
                    ],
                ),
            ],
            # Table already exists. See core\migrations\0045_remove_link_setting_remove_setting_supplier_and_more.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name='setting',
                    constraint=models.UniqueConstraint(fields=('name', 'supplier'), name='name_supplier_constraint'),
                ),
            ],
            # Table already exists. See core\migrations\0045_remove_link_setting_remove_setting_supplier_and_more.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name='link',
                    constraint=models.UniqueConstraint(fields=('setting', 'key'), name='product-field-constraint'),
                ),
            ],
            # Table already exists. See core\migrations\0045_remove_link_setting_remove_setting_supplier_and_more.py
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name='supplierproduct',
                    constraint=models.UniqueConstraint(fields=('supplier', 'article', 'name'), name='sp_uniqe_supplier_article_name'),
                ),
            ],
            # Table already exists. See core\migrations\0045_remove_link_setting_remove_setting_supplier_and_more.py
            database_operations=[],
        ),
    ]
