# Generated by Django 5.2.5 on 2026-03-21 07:02

import django.core.validators
import django.db.models.deletion
import supplier_product_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_product_manager', '0001_initial'),
        ('supplier_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('sheet_name', models.CharField(verbose_name='Название листа')),
                ('create_new', models.BooleanField(default=False, verbose_name='Создавать если нет')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='supplier_manager.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(null=True)),
                ('key', models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('description', 'Описание'), ('category', 'Категория'), ('manufacturer', 'Производитель'), ('discount', 'Группа скидок'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('rrp', 'РРЦ в валюте поставщика'), ('discount_price', 'Цена со скидкой в валюте поставщика')])),
                ('value', models.CharField(null=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='supplier_product_manager.setting')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=supplier_product_manager.models.setting_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'xlsm'])], verbose_name='Файл')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Не загружен'), (1, 'Загружен'), (-1, 'Ошибка')], default=0, verbose_name='Статус загрузки')),
                ('logs', models.CharField(blank=True, null=True, verbose_name='Журнал загрузки')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierfiles', to='supplier_product_manager.setting', verbose_name='Настройка')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(verbose_name='Артикул поставщика')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток')),
                ('supplier_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена поставщика в валюте поставщика')),
                ('rrp', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='РРЦ в валюте поставщика')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена со скидкой в валюте поставщика')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplierproducts', to='supplier_manager.category', verbose_name='Категория')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplierproducts', to='supplier_manager.discount', verbose_name='Группа скидок')),
                ('main_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplierproducts', to='main_product_manager.mainproduct', verbose_name='sku')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplierproducts', to='supplier_manager.manufacturer', verbose_name='Производитель')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplierproducts', to='supplier_manager.supplier', verbose_name='Поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='DictItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(verbose_name='Если')),
                ('value', models.CharField(verbose_name='То')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dicts', to='supplier_product_manager.link', verbose_name='Столбец')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('link', 'key', 'value'), name='link-dict-constraint')],
            },
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('name', 'supplier'), name='name_supplier_constraint'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('setting', 'key'), name='link-field-constraint'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'article', 'name'), name='sp_uniqe_supplier_article_name'),
        ),
    ]
