# Generated by Django 5.2.5 on 2025-12-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0001_initial'),
        ('supplier_manager', '0001_initial'),
        ('supplier_product_manager', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='setting',
                    name='supplier',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_manager.supplier'),
                ),
            ],
            database_operations=[
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='supplierproduct',
                    name='category',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_manager.category', verbose_name='Категория'),
                ),
            ],
            database_operations=[
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='supplierproduct',
                    name='discounts',
                    field=models.ManyToManyField(related_name='products', to='supplier_manager.discount', verbose_name='Группа скидок'),
                ),
            ],
            database_operations=[
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='supplierproduct',
                    name='main_product',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_product', to='main_product_manager.mainproduct', verbose_name='sku'),
                ),
            ],
            database_operations=[
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='supplierproduct',
                    name='manufacturer',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_product', to='supplier_manager.manufacturer', verbose_name='Производитель'),
                ),
            ],
            database_operations=[
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='supplierproduct',
                    name='supplier',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_product', to='supplier_manager.supplier', verbose_name='Поставщик'),
                ),
            ],
            database_operations=[
            ],
        ),
    ]
