# Generated by Django 5.2.5 on 2026-03-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='ignore_name',
            field=models.BooleanField(default=False, verbose_name='Игнорировать название при создании'),
        ),
    ]
