# Generated by Django 5.2.5 on 2025-12-03 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0005_alter_mainproduct_price_updated_at_and_more'),
        ('supplier_product_manager', '0002_alter_setting_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='main_product_manager.mainproduct', verbose_name='sku'),
        ),
    ]
