# Generated by Django 5.2.12 on 2026-04-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0002_setting_ignore_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='index_row',
            field=models.IntegerField(null=True, verbose_name='Ряд для индексации'),
        ),
    ]
