# Generated by Django 5.2.5 on 2025-12-21 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0003_alter_supplierproduct_main_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'xlsm'])], verbose_name='Файл')),
                ('status', models.IntegerField(choices=[(0, 'Не загружен'), (1, 'Загружен'), (-1, 'Ошибка')], verbose_name='Статус загрузки')),
                ('logs', models.CharField(verbose_name='Журнал загрузки')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_file', to='supplier_product_manager.setting')),
            ],
        ),
    ]
