# Generated by Django 5.2.12 on 2026-04-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0003_setting_index_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='index_row',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ряд для индексации'),
        ),
    ]