# Generated by Django 5.2.12 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0004_alter_setting_index_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfile',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'В очереди'), (2, 'В процессе'), (1, 'Успешно'), (-1, 'Ошибка')], default=0, verbose_name='Статус загрузки'),
        ),
    ]
