# Generated by Django 5.2.5 on 2025-12-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0004_supplierfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfile',
            name='logs',
            field=models.CharField(null=True, verbose_name='Журнал загрузки'),
        ),
        migrations.AlterField(
            model_name='supplierfile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Не загружен'), (1, 'Загружен'), (-1, 'Ошибка')], null=True, verbose_name='Статус загрузки'),
        ),
    ]
