# Generated by Django 5.2.5 on 2025-12-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0005_alter_supplierfile_logs_alter_supplierfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfile',
            name='logs',
            field=models.CharField(blank=True, null=True, verbose_name='Журнал загрузки'),
        ),
        migrations.AlterField(
            model_name='supplierfile',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_file', to='supplier_product_manager.setting', verbose_name='Настройка'),
        ),
        migrations.AlterField(
            model_name='supplierfile',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Не загружен'), (1, 'Загружен'), (-1, 'Ошибка')], null=True, verbose_name='Статус загрузки'),
        ),
    ]
