# Generated by Django 5.2.5 on 2025-12-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0006_alter_supplierfile_logs_alter_supplierfile_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfile',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Не загружен'), (1, 'Загружен'), (-1, 'Ошибка')], default=0, verbose_name='Статус загрузки'),
        ),
    ]
