# Generated by Django 5.2.5 on 2026-08-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0006_copysupplierproductstomainrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='pim_id',
            field=models.CharField(blank=True, null=True, verbose_name='Id для системы Pim'),
        ),
    ]
