# Generated by Django 5.2.5 on 2026-01-15 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0008_alter_supplierfile_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfile',
            name='setting',
            field=models.ForeignKey(blank=True, default=(None, 'Новая настройка'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_file', to='supplier_product_manager.setting', verbose_name='Настройка'),
        ),
    ]
