# Generated by Django 5.2.5 on 2026-01-22 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0009_alter_supplierfile_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dicts', to='supplier_product_manager.link', verbose_name='Столбец'),
        ),
        migrations.AddConstraint(
            model_name='dict',
            constraint=models.UniqueConstraint(fields=('key', 'value'), name='dict-constraint'),
        ),
    ]
