# Generated by Django 5.2.5 on 2026-09-23 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0011_retire_category_and_manufacturer'),
        ('supplier_product_manager', '0010_drop_category_and_manufacturer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('applied', 'Применён'), ('refused', 'Отказ'), ('failed', 'Ошибка')], default='running', max_length=16, verbose_name='Статус')),
                ('message', models.TextField(blank=True, default='', verbose_name='Сообщение')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('mapped_keys', models.JSONField(blank=True, default=list, verbose_name='Сопоставленные поля')),
                ('rows_in_sheet', models.PositiveIntegerField(blank=True, null=True, verbose_name='Строк на листе')),
                ('rows_with_article', models.PositiveIntegerField(blank=True, null=True, verbose_name='Строк с артикулом')),
                ('rows_with_values', models.PositiveIntegerField(blank=True, null=True, verbose_name='Строк со значениями')),
                ('rows_without_name', models.PositiveIntegerField(blank=True, null=True, verbose_name='Отброшено без названия')),
                ('rows_unmatched', models.PositiveIntegerField(blank=True, null=True, verbose_name='Не совпало с товарами')),
                ('duplicates', models.PositiveIntegerField(blank=True, null=True, verbose_name='Дубликатов')),
                ('covered', models.PositiveIntegerField(blank=True, null=True, verbose_name='Покрыто строк')),
                ('covered_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Покрыто с ценой')),
                ('covered_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Покрыто с остатком')),
                ('created', models.PositiveIntegerField(blank=True, null=True, verbose_name='Создано')),
                ('updated', models.PositiveIntegerField(blank=True, null=True, verbose_name='Обновлено')),
                ('missing', models.PositiveIntegerField(blank=True, null=True, verbose_name='Нет в файле (обнулено)')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to='supplier_product_manager.setting', verbose_name='Настройка')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_runs', to='supplier_manager.supplier', verbose_name='Поставщик')),
                ('supplier_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to='supplier_product_manager.supplierfile', verbose_name='Файл')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Импорт прайса',
                'verbose_name_plural': 'Импорты прайсов',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['setting', 'status', '-started_at'], name='importrun_setting_history')],
            },
        ),
    ]
