# Generated by Django 5.2.5 on 2026-01-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0011_rename_dict_dictitem_alter_link_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dictitem',
            name='dict-constraint',
        ),
        migrations.AddConstraint(
            model_name='dictitem',
            constraint=models.UniqueConstraint(fields=('link', 'key', 'value'), name='link-dict-constraint'),
        ),
    ]
