# Generated by Django 5.2.5 on 2026-09-23 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0011_importrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_import_runs', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='guard_reasons',
            field=models.JSONField(blank=True, default=list, verbose_name='Причины проверки'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Сигнатура настройки'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='status',
            field=models.CharField(choices=[('running', 'Выполняется'), ('applied', 'Применён'), ('refused', 'Отказ'), ('failed', 'Ошибка'), ('pending', 'Ждёт подтверждения'), ('cancelled', 'Отменён'), ('superseded', 'Заменён')], default='running', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supplierfile',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'В очереди'), (2, 'В процессе'), (1, 'Успешно'), (-1, 'Ошибка'), (3, 'Ждёт подтверждения')], default=0, verbose_name='Статус загрузки'),
        ),
    ]
