# Generated by Django 5.2.5 on 2026-01-26 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0012_remove_dictitem_dict_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='discounts',
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('rrp', 'РРЦ в валюте поставщика')]),
        ),
        migrations.AlterField(
            model_name='supplierfile',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_files', to='supplier_product_manager.setting', verbose_name='Настройка'),
        ),
    ]
