# Generated by Django 5.2.5 on 2026-09-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0012_import_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='article_conflicts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Артикулов с разными названиями'),
        ),
    ]
