# Generated by Django 5.2.5 on 2026-01-26 15:05

import django.core.validators
import supplier_product_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0013_remove_supplierproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfile',
            name='file',
            field=models.FileField(upload_to=supplier_product_manager.models.setting_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'xlsm'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='rrp',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='РРЦ в валюте поставщика'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='stock',
            field=models.PositiveIntegerField(null=True, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Цена поставщика в валюте поставщика'),
        ),
    ]
