# Generated by Django 5.2.5 on 2026-09-23 07:48
"""Setting.ignore_name -> Setting.match_by_article.

ignore_name only acted together with create_new: an article already in the
database took its data into the existing rows (with their names) instead of
creating a new product. match_by_article does that for every import and also
renames a single existing row when the file's name changed. So only settings
with ignore_name AND create_new get the new flag; ignore_name without
create_new had no effect, and those settings keep matching by article + name.
"""

from django.db import migrations, models


def ignore_name_to_match_by_article(apps, schema_editor):
    Setting = apps.get_model('supplier_product_manager', 'Setting')
    moved = Setting.objects.filter(ignore_name=True, create_new=True).update(match_by_article=True)
    left = Setting.objects.filter(ignore_name=True, create_new=False).count()
    print(f'\n  0014: сопоставление по артикулу включено у настроек: {moved}'
          f' (ignore_name без create_new ни на что не влиял, не перенесено: {left})')


def match_by_article_to_ignore_name(apps, schema_editor):
    Setting = apps.get_model('supplier_product_manager', 'Setting')
    Setting.objects.filter(match_by_article=True).update(ignore_name=True)


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0013_importrun_article_conflicts'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='match_by_article',
            field=models.BooleanField(default=False, verbose_name='Артикул уникален — сопоставлять только по артикулу'),
        ),
        migrations.RunPython(ignore_name_to_match_by_article, match_by_article_to_ignore_name),
        migrations.RemoveField(
            model_name='setting',
            name='ignore_name',
        ),
        migrations.AddField(
            model_name='importrun',
            name='articles_multi_db',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Артикулов с несколькими товарами в базе'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='renamed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Переименовано'),
        ),
    ]
