# Generated by Django 5.2.5 on 2026-01-27 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0004_alter_supplier_options'),
        ('supplier_product_manager', '0014_alter_supplierfile_file_alter_supplierproduct_rrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='supplier_manager.discount', verbose_name='Группа скидок'),
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('manufacturer', 'Производитель'), ('discount', 'Группа скидок'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('rrp', 'РРЦ в валюте поставщика')]),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_products', to='supplier_manager.manufacturer', verbose_name='Производитель'),
        ),
    ]
