# Generated by Django 5.2.5 on 2026-09-23 12:12
"""SupplierProduct.source_settings: which settings supply a row.

Backfill: nothing records which file a row came from, so every row is linked to
every working setting of its supplier (one with at least one mapped column).
For a supplier with one setting that is exact. For a supplier with several, the
first import of each setting behaves as before this change — it clears its
fields on rows missing from its file — and unlinks those rows, so after one
round of imports the links are exact.

Rows of suppliers with no working setting stay unlinked. They are "nobody's"
rows, which any import of their supplier handles the old way
(functions.own_rows), so leaving them unlinked is safe.
"""

from django.db import migrations, models


def link_rows_to_supplier_settings(apps, schema_editor):
    SupplierProduct = apps.get_model('supplier_product_manager', 'SupplierProduct')
    Setting = apps.get_model('supplier_product_manager', 'Setting')
    Link = apps.get_model('supplier_product_manager', 'Link')
    through = SupplierProduct.source_settings.through._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'''
            INSERT INTO {through} (supplierproduct_id, setting_id)
            SELECT sp.id, s.id
              FROM {SupplierProduct._meta.db_table} sp
              JOIN {Setting._meta.db_table} s ON s.supplier_id = sp.supplier_id
             WHERE EXISTS (
                   SELECT 1 FROM {Link._meta.db_table} l
                    WHERE l.setting_id = s.id
                      AND (COALESCE(l.value, '') <> '' OR COALESCE(l.initial, '') <> ''))
            ON CONFLICT DO NOTHING
        ''')
        linked = cursor.rowcount
    print(f'\n  0015: связей «строка прайса — настройка» создано: {linked}')


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0014_match_by_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='source_settings',
            field=models.ManyToManyField(blank=True, related_name='supplied_products', to='supplier_product_manager.setting', verbose_name='Поставляют настройки'),
        ),
        # Reverse is a no-op: removing the field drops the table with the links.
        migrations.RunPython(link_rows_to_supplier_settings, migrations.RunPython.noop),
    ]
