# Generated by Django 5.2.5 on 2026-01-27 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0004_alter_supplier_options'),
        ('supplier_product_manager', '0015_supplierproduct_discount_alter_link_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='supplier_manager.supplier'),
        ),
    ]
