# Generated by Django 5.2.5 on 2026-09-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0015_supplierproduct_source_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='missing_linked',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Из них привязаны к ГП'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='price_changes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Изменения цен'),
        ),
    ]
