# Generated by Django 5.2.5 on 2026-09-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0016_importrun_missing_linked_price_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='possible_renames',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Похоже на переименование'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='whitespace_ambiguous',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Отличаются пробелами от нескольких товаров'),
        ),
    ]
