# Generated by Django 5.2.5 on 2026-01-30 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0016_alter_setting_supplier'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='link',
            name='product-field-constraint',
        ),
        migrations.AlterField(
            model_name='link',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='supplier_product_manager.setting'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('setting', 'key'), name='link-field-constraint'),
        ),
    ]
