# Generated by Django 5.2.5 on 2026-09-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0017_importrun_possible_renames'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='missing_columns',
            field=models.JSONField(blank=True, default=list, verbose_name='Нет столбцов'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='unparsed_numbers',
            field=models.JSONField(blank=True, default=dict, verbose_name='Не распознаны как числа'),
        ),
    ]
