# Generated by Django 5.2.5 on 2026-01-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0017_remove_link_product_field_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='value',
            field=models.CharField(null=True),
        ),
    ]
