# Generated by Django 5.2.5 on 2026-02-02 15:17

import django.core.validators
import supplier_product_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0018_alter_link_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfile',
            name='file',
            field=models.FileField(max_length=255, upload_to=supplier_product_manager.models.setting_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'xlsm'])], verbose_name='Файл'),
        ),
    ]
