# Generated by Django 5.2.5 on 2026-02-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0019_alter_supplierfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='update_main',
            field=models.BooleanField(default=True, verbose_name='Обновлять товары ГП'),
        ),
    ]
