# Generated by Django 5.2.5 on 2026-02-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0020_alter_setting_update_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='update_main',
            field=models.BooleanField(default=True, verbose_name='Обновлять главный прайс'),
        ),
    ]
