# Generated by Django 5.2.5 on 2026-02-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0021_alter_setting_update_main'),
    ]

    operations = [
        
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='setting',
                    name='update_main',
                ),
            ],
            # Table already exists. See core\migrations\0045_remove_link_setting_remove_setting_supplier_and_more.py
            database_operations=[],
        ),
    ]
