# Generated by Django 5.2.5 on 2026-02-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0022_remove_setting_update_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Цена со скидкой в валюте поставщика'),
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('manufacturer', 'Производитель'), ('discount', 'Группа скидок'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('rrp', 'РРЦ в валюте поставщика'), ('discount_price', 'Цена со скидкой в валюте поставщика')]),
        ),
        migrations.RemoveField(
            model_name='setting',
            name='add_main_products',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='priced_only',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='differ_by_name',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='update_main_content',
        ),
    ]
