# Generated by Django 5.2.5 on 2026-02-04 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0023_supplierproduct_discount_price_alter_link_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierfile',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplierfiles', to='supplier_product_manager.setting', verbose_name='Настройка'),
        ),
    ]
