# Generated by Django 5.2.5 on 2026-02-05 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0018_mainproduct_discount_price'),
        ('supplier_manager', '0004_alter_supplier_options'),
        ('supplier_product_manager', '0024_alter_supplierfile_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplierproducts', to='supplier_manager.discount', verbose_name='Группа скидок'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplierproducts', to='main_product_manager.mainproduct', verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplierproducts', to='supplier_manager.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplierproducts', to='supplier_manager.supplier', verbose_name='Поставщик'),
        ),
    ]
