# Generated by Django 5.2.5 on 2026-02-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0025_alter_supplierproduct_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='create_main',
            field=models.BooleanField(default=False, verbose_name='Создавать товары в ГП'),
        ),
    ]
