# Generated by Django 5.2.5 on 2026-02-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0026_setting_create_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='create_main',
        ),
    ]
