# Generated by Django 5.2.5 on 2026-02-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0027_remove_setting_create_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='create_new',
            field=models.BooleanField(default=False, verbose_name='Создавать если нет'),
        ),
    ]
