# Generated by Django 5.2.5 on 2026-02-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0028_setting_create_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена со скидкой в валюте поставщика'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='РРЦ в валюте поставщика'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена поставщика в валюте поставщика'),
        ),
    ]
