# Generated by Django 5.2.5 on 2026-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product_manager', '0029_alter_supplierproduct_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
