# Generated by Django 5.2.5 on 2026-02-13 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0009_supplier_grouping_priority'),
        ('supplier_product_manager', '0030_supplierproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplierproducts', to='supplier_manager.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('description', 'Описание'), ('category', 'Категория'), ('manufacturer', 'Производитель'), ('discount', 'Группа скидок'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('rrp', 'РРЦ в валюте поставщика'), ('discount_price', 'Цена со скидкой в валюте поставщика')]),
        ),
    ]
