# Generated by Django 5.2.5 on 2025-12-02 10:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_manager', '0001_initial'),
    ]

    operations = [
        
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PriceManager',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(unique=True, verbose_name='Название')),
                        ('has_rrp', models.BooleanField(blank=True, choices=[(None, 'Без разницы'), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Есть РРЦ')),
                        ('source', models.CharField(choices=[('rrp', 'РРЦ в валюте поставщика'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], verbose_name='От какой цены считать')),
                        ('dest', models.CharField(choices=[('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], verbose_name='Какую цену считать')),
                        ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена от')),
                        ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена до')),
                        ('markup', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Накрутка')),
                        ('increase', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Надбавка')),
                        ('discounts', models.ManyToManyField(blank=True, related_name='price_managers', to='supplier_manager.discount', verbose_name='Группа скидок')),
                        ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_managers', to='supplier_manager.supplier', verbose_name='Поставщик')),
                    ],
                ),
            ],
            database_operations=[
            ],
        ),
    ]
