# Generated by Django 5.2.5 on 2026-03-21 07:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_product_manager', '0001_initial'),
        ('supplier_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                ('has_rrp', models.BooleanField(blank=True, choices=[(None, 'Без разницы'), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Есть РРЦ')),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('source', models.CharField(choices=[(None, 'Не указано'), ('fixed_price', 'Фиксированная цена'), ('rrp', 'РРЦ в валюте поставщика'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1'), ('discount_price', 'Цена со скидкой')], verbose_name='От какой цены считать')),
                ('dest', models.CharField(choices=[(None, 'Не указано'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1'), ('discount_price', 'Цена со скидкой')], verbose_name='Какую цену считать')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена от')),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена до')),
                ('fixed_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Значение фиксированной цены')),
                ('markup', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Накрутка')),
                ('increase', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Надбавка')),
                ('deprecated', models.BooleanField(default=False, verbose_name='Устаревший менеджер цен')),
                ('categories', models.ManyToManyField(blank=True, related_name='pricemanagers', to='supplier_manager.category', verbose_name='Категории')),
                ('discounts', models.ManyToManyField(blank=True, related_name='pricemanagers', to='supplier_manager.discount', verbose_name='Группы скидок')),
                ('supplier', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricemanagers', to='supplier_manager.supplier', verbose_name='Поставщик')),
            ],
            options={
                'ordering': ['dest', 'source'],
            },
        ),
        migrations.CreateModel(
            name='PriceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('source', models.CharField(blank=True, choices=[(None, 'Фиксированная цена'), ('rrp', 'РРЦ в валюте поставщика'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1'), ('discount_price', 'Цена со скидкой')], null=True, verbose_name='От какой цены считать')),
                ('dest', models.CharField(blank=True, choices=[('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1'), ('discount_price', 'Цена со скидкой')], null=True, verbose_name='Какую цену считать')),
                ('markup', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Накрутка')),
                ('increase', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Надбавка')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фиксированная цена (тг)')),
                ('deprecated', models.BooleanField(default=False, verbose_name='Устаревшая наценка')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricetags', to='main_product_manager.mainproduct', verbose_name='Товар главного прайса')),
                ('p_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricetags', to='product_price_manager.pricemanager', verbose_name='Менеджер наценок')),
            ],
            options={
                'verbose_name': 'Наценка',
                'verbose_name_plural': 'Наценки',
                'constraints': [models.UniqueConstraint(fields=('mp', 'p_manager', 'dest'), name='pricetag_constraint')],
            },
        ),
    ]
