# Generated by Django 5.2.5 on 2026-09-04 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price_manager', '0002_alter_pricemanager_dest_alter_pricemanager_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemanager',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-100)], verbose_name='Накрутка'),
        ),
        migrations.AlterField(
            model_name='pricetag',
            name='markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-100)], verbose_name='Накрутка'),
        ),
    ]
