# Generated by Django 5.2.5 on 2025-12-05 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price_manager', '0002_uniquepricemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquepricemanager',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фиксированная цена'),
        ),
        migrations.AlterField(
            model_name='uniquepricemanager',
            name='source',
            field=models.CharField(choices=[(None, 'Фиксированная цена'), ('rrp', 'РРЦ в валюте поставщика'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], null=True, verbose_name='От какой цены считать'),
        ),
    ]
