# Generated by Django 5.2.5 on 2025-12-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0007_alter_mainproduct_special_prices'),
        ('product_price_manager', '0004_alter_uniquepricemanager_dest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniquePriceManager',
            new_name='SpecialPrice',
        ),
    ]
