# Generated by Django 5.2.5 on 2026-01-01 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price_manager', '0007_remove_pricemanager_discounts_and_more'),
        ('supplier_manager', '0002_supplier_msg_available_supplier_msg_navailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemanager',
            name='dest',
            field=models.CharField(choices=[(None, 'Не указано'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], verbose_name='Какую цену считать'),
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Значение фиксированной цены'),
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='source',
            field=models.CharField(choices=[(None, 'Не указано'), ('fixed_price', 'Фиксированная цена'), ('rrp', 'РРЦ в валюте поставщика'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], verbose_name='От какой цены считать'),
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='supplier',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='price_managers', to='supplier_manager.supplier', verbose_name='Поставщик'),
            preserve_default=False,
        ),
    ]
