# Generated by Django 5.2.5 on 2026-01-13 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price_manager', '0008_alter_pricemanager_dest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricemanager',
            options={'ordering': ['dest', 'source']},
        ),
        migrations.AlterField(
            model_name='pricetag',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фиксированная цена (тг)'),
        ),
    ]
