# Generated by Django 5.2.5 on 2026-01-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price_manager', '0009_alter_pricemanager_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemanager',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='pricemanager',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
