# Generated by Django 5.2.5 on 2026-01-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price_manager', '0010_pricemanager_date_from_pricemanager_date_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetag',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='pricetag',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
