# Generated by Django 5.2.5 on 2026-01-15 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price_manager', '0011_pricetag_date_from_pricetag_date_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetag',
            name='p_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricetags', to='product_price_manager.pricemanager', verbose_name='Менеджер наценок'),
        ),
    ]
