# Generated by Django 5.2.5 on 2026-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price_manager', '0012_alter_pricetag_p_manager'),
        ('supplier_manager', '0004_alter_supplier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemanager',
            name='discounts',
            field=models.ManyToManyField(null=True, related_name='pricemanagers', to='supplier_manager.discount', verbose_name='Группы скидок'),
        ),
    ]
