# Generated by Django 5.2.5 on 2026-01-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price_manager', '0013_pricemanager_discounts'),
        ('supplier_manager', '0004_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemanager',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='pricemanagers', to='supplier_manager.discount', verbose_name='Группы скидок'),
        ),
    ]
