# Generated by Django 5.2.5 on 2026-02-01 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0014_alter_mainproduct_basic_price_and_more'),
        ('product_price_manager', '0014_alter_pricemanager_discounts'),
        ('supplier_manager', '0004_alter_supplier_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialPrice',
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='supplier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricemanagers', to='supplier_manager.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddConstraint(
            model_name='pricetag',
            constraint=models.UniqueConstraint(fields=('mp', 'p_manager', 'dest'), name='pricetag_constraint'),
        ),
    ]
