# Generated by Django 5.2.5 on 2026-02-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price_manager', '0015_delete_specialprice_alter_pricemanager_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemanager',
            name='deprecated',
            field=models.BooleanField(default=False, verbose_name='Устаревший менеджер цен'),
        ),
        migrations.AddField(
            model_name='pricetag',
            name='deprecated',
            field=models.BooleanField(default=False, verbose_name='Устаревшая наценка'),
        ),
    ]
