# Generated by Django 5.2.5 on 2026-02-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price_manager', '0016_pricemanager_deprecated_pricetag_deprecated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemanager',
            name='dest',
            field=models.CharField(choices=[(None, 'Не указано'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1'), ('discount_price', 'Цена со скидкой')], verbose_name='Какую цену считать'),
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='source',
            field=models.CharField(choices=[(None, 'Не указано'), ('fixed_price', 'Фиксированная цена'), ('rrp', 'РРЦ в валюте поставщика'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1'), ('discount_price', 'Цена со скидкой')], verbose_name='От какой цены считать'),
        ),
        migrations.AlterField(
            model_name='pricetag',
            name='dest',
            field=models.CharField(blank=True, choices=[('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1'), ('discount_price', 'Цена со скидкой')], null=True, verbose_name='Какую цену считать'),
        ),
        migrations.AlterField(
            model_name='pricetag',
            name='source',
            field=models.CharField(blank=True, choices=[(None, 'Фиксированная цена'), ('rrp', 'РРЦ в валюте поставщика'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1'), ('discount_price', 'Цена со скидкой')], null=True, verbose_name='От какой цены считать'),
        ),
    ]
