# Generated by Django 5.2.5 on 2026-02-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price_manager', '0017_alter_pricemanager_dest_alter_pricemanager_source_and_more'),
        ('supplier_manager', '0004_alter_supplier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemanager',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='pricemanagers', to='supplier_manager.category', verbose_name='Категории'),
        ),
    ]
