# Generated by Django 5.2.5 on 2026-09-23 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('page_url', models.CharField(blank=True, max_length=500, verbose_name='Страница')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Задача создана'), ('failed', 'Ошибка отправки')], default='pending', max_length=16, verbose_name='Статус')),
                ('bitrix_task_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Задача в Bitrix24')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Задача создана')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Обращение к разработчикам',
                'verbose_name_plural': 'Обращения к разработчикам',
                'ordering': ('-created_at',),
            },
        ),
    ]
