# Generated by Django 5.2.5 on 2026-09-02 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(allow_unicode=True, max_length=64, unique=True, verbose_name='Ключ')),
                ('label', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип цены',
                'verbose_name_plural': 'Типы цен',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('fixed', 'Фиксированная'), ('formula', 'Формула')], max_length=32, verbose_name='Режим')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Параметры')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет')),
                ('price_from', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Цена от')),
                ('price_to', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Цена до')),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_rules', to='product.category', verbose_name='Категория')),
                ('dest_price_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dest_rules', to='pricing.pricetype', verbose_name='Тип цены-назначения')),
                ('source_price_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_rules', to='pricing.pricetype', verbose_name='Тип цены-источника')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='supplier.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Правило ценообразования',
                'verbose_name_plural': 'Правила ценообразования',
                'ordering': ['supplier', 'priority'],
            },
        ),
    ]
