# Generated by Django 5.2.5 on 2026-09-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(max_length=128, unique=True, verbose_name='Номер PIM (артикул)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pim_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Id товара в PIM'),
        ),
    ]
