# Generated by Django 5.2.5 on 2026-05-02 08:43

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
            },
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Название цены')),
            ],
        ),
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Название цены')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='default', max_length=200, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(serialize=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Контент')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='product.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Значение')),
                ('mute', models.BooleanField(default=False, verbose_name='Устаревшая')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='product.price', verbose_name='Источник цены')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product', verbose_name='Продукт')),
                ('ptype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.pricetype', verbose_name='Тип цены')),
            ],
            options={
                'verbose_name': 'Цена',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.PositiveIntegerField(null=True, verbose_name='Значение')),
                ('mute', models.BooleanField(default=False, verbose_name='Устаревший')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='product.stock', verbose_name='Источник цены')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.product', verbose_name='Продукт')),
                ('stype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.stocktype', verbose_name='Тип остатка')),
            ],
            options={
                'verbose_name': 'Остаток',
            },
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
