# Generated by Django 5.2.5 on 2026-09-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.CharField(max_length=128, unique=True, verbose_name='Номер PIM (артикул)'),
        ),
        migrations.AddField(
            model_name='product',
            name='pim_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='Id товара в PIM'),
        ),
        migrations.AddField(
            model_name='product',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Сырые данные PIM'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_chars_gin_idx',
        ),
    ]
