# Generated by Django 5.2.5 on 2026-09-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_number_alter_product_pim_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Номер PIM (артикул)'),
        ),
    ]
