# Generated by Django 5.2.5 on 2026-05-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_manufacturer_pricetype_stocktype_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
