# Generated by Django 5.2.5 on 2026-05-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='contenttypes',
        ),
    ]
