# Generated by Django 5.2.5 on 2026-05-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0006_contenttype_remove_link_contentitem_and_more'),
        ('product', '0004_remove_category_contenttypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentType',
        ),
    ]
