# Generated by Django 5.2.5 on 2026-05-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0006_contenttype_remove_link_contentitem_and_more'),
        ('product', '0005_delete_contenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='contenttypes',
            field=models.ManyToManyField(related_name='categories', to='dataframe.contenttype', verbose_name='Тип конента'),
        ),
    ]
