# Generated by Django 5.2.5 on 2026-05-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_charmutationjob_progress'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='characteristicmutationjob',
            new_name='product_cha_user_id_13adea_idx',
            old_name='product_charmut_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='importjob',
            new_name='product_imp_user_id_898108_idx',
            old_name='product_imp_user_id_created_idx',
        ),
    ]
