# Generated by Django 5.2.5 on 2026-09-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productsetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='basic_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Базовая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AddField(
            model_name='product',
            name='kaspi_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена Каспи'),
        ),
        migrations.AddField(
            model_name='product',
            name='m_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена ИМ'),
        ),
        migrations.AddField(
            model_name='product',
            name='pim_pushed_prices',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Цены, отправленные в PIM'),
        ),
        migrations.AddField(
            model_name='product',
            name='prices_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Цены пересчитаны'),
        ),
        migrations.AddField(
            model_name='product',
            name='prime_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Себестоимость'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Оптовая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Оптовая цена доп.'),
        ),
    ]
