# Generated by Django 5.2.5 on 2026-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='РРЦ, тг'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена поставщика со скидкой, тг'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена поставщика, тг'),
        ),
    ]
