# Generated by Django 5.2.4 on 2025-08-11 06:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                ('value', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Тенге')),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])], verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(verbose_name='Артикул поставщика')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                ('supplier_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена поставщика')),
                ('rmp_raw', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РРЦ в валюте закупа')),
                ('rmp_kzt', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РРЦ в тенге')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
            },
        ),
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.product')),
                ('sku', models.CharField(unique=True, verbose_name='Артикуль товара')),
            ],
            options={
                'verbose_name': 'Главный продукт',
            },
            bases=('core.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manufacturer', verbose_name='Производитель'),
        ),
        migrations.CreateModel(
            name='ManufacturerDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Вариация')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Словарь Производителя',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('sheet_name', models.CharField(verbose_name='Название листа')),
                ('priced_only', models.BooleanField(default=True, verbose_name='Не включать поля без цены')),
                ('id_as_sku', models.BooleanField(default=False, verbose_name='Использывать артикул как SKU')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(choices=[(None, 'Не включать')])),
                ('column', models.CharField()),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setting')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.product')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mainproduct', verbose_name='sku')),
            ],
            bases=('core.product',),
        ),
    ]
