# Generated by Django 5.2.5 on 2025-08-21 12:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                ('value', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Тенге')),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])], verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(null=True)),
                ('key', models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('category', 'Категория'), ('manufacturer', 'Производитель'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика'), ('rmp_raw', 'РРЦ в валюте закупа'), ('rmp_kzt', 'РРЦ в тенге')])),
                ('value', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Подкатегория для')),
            ],
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(verbose_name='Если')),
                ('value', models.CharField(verbose_name='То')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.link', verbose_name='Столбец')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Вариация')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='md_manufacturer_ptr', to='core.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Словарь Производителя',
            },
        ),
        migrations.CreateModel(
            name='PriceManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                ('source', models.CharField(choices=[('rmp_kzt', 'РРЦ в тенге (поставщика)'), ('supplier_price', 'Цена поставщика'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('rmp', 'РРЦ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], verbose_name='От какой цены считать')),
                ('dest', models.CharField(choices=[('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], verbose_name='Какую цену считать')),
                ('price_from', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена от')),
                ('price_to', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена до')),
                ('markup', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Накрутка')),
                ('increase', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Надбавка')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_category_ptr', to='core.category', verbose_name='Категория')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_supplier_ptr', to='core.supplier', verbose_name='Поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('sheet_name', models.CharField(verbose_name='Название листа')),
                ('priced_only', models.BooleanField(default=True, verbose_name='Не включать поля без цены')),
                ('id_as_sku', models.BooleanField(default=True, verbose_name='Использывать артикул как SKU')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setting'),
        ),
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(unique=True, verbose_name='Артикул товара')),
                ('article', models.CharField(verbose_name='Артикул поставщика')),
                ('name', models.CharField(verbose_name='Название')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Вес')),
                ('prime_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Себестоимость')),
                ('rmp', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РРЦ')),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Оптовая цена')),
                ('basic_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Базовая цена')),
                ('m_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена ИМ')),
                ('wholesale_price_extra', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Оптовая цена доп.')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Длина')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ширина')),
                ('depth', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Глубина')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_manufacturer_ptr', to='core.manufacturer', verbose_name='Производитель')),
                ('price_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_price_manager_ptr', to='core.pricemanager', verbose_name='Наценка')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_supplier_ptr', to='core.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Главный продукт',
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(verbose_name='Артикул поставщика')),
                ('name', models.CharField(verbose_name='Название')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('supplier_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена поставщика')),
                ('rmp_raw', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РРЦ в валюте закупа')),
                ('rmp_kzt', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РРЦ в тенге')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sp_currency_ptr', to='core.currency', verbose_name='Валюта')),
                ('main_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_main_product_ptr', to='core.mainproduct', verbose_name='sku')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_manufacturer_ptr', to='core.manufacturer', verbose_name='Производитель')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_supplier_ptr', to='core.supplier', verbose_name='Поставщик')),
            ],
        ),
    ]
