
# Generated by Django 5.2.4 on 2025-08-11 06:50
# Создает валюту Тенге при инициализации
from django.db import migrations

def create_initial_currency(apps, schema_editor):
    Currency = apps.get_model('core', 'Currency')
    Currency.objects.create(name='KZT', value=1)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_currency),
    ]
