# Generated by Django 5.2.5 on 2025-08-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250821_1536'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'article', 'name'), name='uniq_supplier_article_name'),
        ),
    ]
