# Generated by Django 5.2.5 on 2026-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_persistentnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRunHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=255, verbose_name='Имя задачи')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('skipped', 'Пропущено (lock)')], max_length=16, verbose_name='Статус')),
                ('started_at', models.DateTimeField(verbose_name='Начало выполнения')),
                ('finished_at', models.DateTimeField(verbose_name='Окончание выполнения')),
                ('duration_ms', models.PositiveIntegerField(verbose_name='Длительность, мс')),
                ('updated_count', models.IntegerField(default=0, verbose_name='Обновлено записей')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История запуска задачи',
                'verbose_name_plural': 'История запусков задач',
                'ordering': ('-started_at',),
            },
        ),
    ]
