# Generated by Django 5.2.4 on 2025-08-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250811_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rmp_kzt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rmp_raw',
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='rmp_kzt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РРЦ в тенге'),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='rmp_raw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РРЦ в валюте закупа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='id_as_sku',
            field=models.BooleanField(default=True, verbose_name='Использывать артикул как SKU'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Подкатегория для')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория'),
        ),
    ]
