# Generated by Django 5.2.5 on 2026-08-17 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taskrunhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentnotification',
            name='level',
            field=models.CharField(choices=[('info', 'Инфо'), ('success', 'Успех'), ('warning', 'Предупреждение'), ('danger', 'Ошибка')], default='info', max_length=16, verbose_name='Уровень'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.alternateproduct', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('file', models.FileField(blank=True, null=True, upload_to='shopping_tabs/', verbose_name='Файл')),
                ('open', models.BooleanField(default=True, verbose_name='Открыта')),
                ('items', models.ManyToManyField(related_name='shopping_tabs', to='core.cartitem', verbose_name='Элементы корзины')),
                ('products', models.ManyToManyField(related_name='shopping_tabs', to='core.alternateproduct', verbose_name='Товары')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_tabs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
            },
        ),
        migrations.DeleteModel(
            name='ShopingTab',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='user_product_constraint'),
        ),
        migrations.AddConstraint(
            model_name='shoppingtab',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='user_name_constraint'),
        ),
    ]
