# Generated by Django 5.2.1 on 2025-08-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_currency_remove_product_rmp_kzt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(verbose_name='Наименование'),
        ),
    ]
