# Generated by Django 5.2.5 on 2025-08-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_supplierproduct_uniq_supplier_article_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplierproduct',
            name='uniq_supplier_article_name',
        ),
        migrations.AddConstraint(
            model_name='mainproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'article', 'name'), name='mp_uniqe_supplier_article_name'),
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'article', 'name'), name='sp_uniqe_supplier_article_name'),
        ),
    ]
