# Generated by Django 5.2.5 on 2025-08-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_currency_remove_product_rmp_kzt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='Dict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(verbose_name='Если')),
                ('value', models.CharField(verbose_name='То')),
                ('link', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.link', verbose_name='Столбец')),
            ],
        ),
    ]
