# Generated by Django 5.2.5 on 2026-08-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_persistentnotification_level_cartitem_and_more'),
        ('main_product_manager', '0004_mainproduct_pim_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='user_product_constraint',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='products',
            field=models.ManyToManyField(related_name='cart_items', to='main_product_manager.mainproduct', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='search_query',
            field=models.JSONField(blank=True, null=True, verbose_name='Поисковый запрос'),
        ),
    ]
