# Generated by Django 5.2.5 on 2025-08-21 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_supplierproduct_uniq_supplier_article_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='pricemanager',
            name='category',
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена от'),
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена до'),
        ),
        migrations.AddField(
            model_name='pricemanager',
            name='Discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_category_ptr', to='core.discount', verbose_name='Группа скидок'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discount', verbose_name='Группа скидок'),
        ),
    ]
