# Generated by Django 5.2.5 on 2025-08-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_name_dict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict',
            name='link',
        ),
        migrations.AddField(
            model_name='dict',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.setting', verbose_name='Столбец'),
        ),
    ]
