# Generated by Django 5.2.5 on 2026-08-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cartitem_user_product_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingtab',
            name='products',
        ),
    ]
