# Generated by Django 5.2.5 on 2025-08-21 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_discount_remove_pricemanager_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricemanager',
            name='Discount',
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier_price_kzt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена поставщика'),
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('category', 'Категория'), ('discount', 'Группа скидок'), ('manufacturer', 'Производитель'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика'), ('supplier_price_kzt', 'Цена поставщика в тенге'), ('rmp_raw', 'РРЦ в валюте закупа'), ('rmp_kzt', 'РРЦ в тенге')]),
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='source',
            field=models.CharField(choices=[('rmp_kzt', 'РРЦ в тенге'), ('supplier_price_kzt', 'Цена поставщика в тенге'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('rmp', 'РРЦ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], verbose_name='От какой цены считать'),
        ),
        migrations.AddField(
            model_name='pricemanager',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_discount_ptr', to='core.discount', verbose_name='Группа скидок'),
        ),
    ]
