# Generated by Django 5.2.5 on 2025-08-13 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_dict_link_dict_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict',
            name='setting',
        ),
        migrations.AddField(
            model_name='dict',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.link', verbose_name='Столбец'),
        ),
    ]
