# Generated by Django 5.2.1 on 2025-08-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_name'),
        ('core', '0006_remove_dict_setting_dict_link'),
    ]

    operations = [
    ]
