# Generated by Django 5.2.5 on 2025-08-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pricemanager_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discount', verbose_name='Группа скидок'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier_price_kzt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена поставщика в тенге'),
        ),
    ]
