# Generated by Django 5.2.5 on 2025-08-15 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_dict_setting_dict_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='column',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='sku',
            field=models.CharField(unique=True, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_ptr', to='core.mainproduct', verbose_name='sku'),
        ),
    ]
