# Generated by Django 5.2.5 on 2026-08-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_shoppingtab_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlternateProduct',
        ),
    ]
