# Generated by Django 5.2.5 on 2025-08-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_link_link_key_rename_column_link_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='initial',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(choices=[('', 'Не включать')]),
        ),
    ]
