# Generated by Django 5.2.5 on 2025-08-22 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mainproduct_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mp_supplier_ptr', to='core.supplier', verbose_name='Поставщик'),
        ),
    ]
