# Generated by Django 5.2.5 on 2026-08-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_alternateproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='search_query',
            field=models.CharField(blank=True, null=True, verbose_name='Поисковый запрос'),
        ),
    ]
