# Generated by Django 5.2.5 on 2025-08-17 07:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_link_initial_alter_link_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproduct',
            name='rmp_kzt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_price',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='sku',
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='basic_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Базовая цена'),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='m_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена ИМ'),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='prime_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Себестоимость'),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='rmp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РРЦ'),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Оптовая цена'),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='wholesale_price_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Оптовая цена доп.'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sp_main_product_ptr', to='core.mainproduct', verbose_name='sku'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='rmp_kzt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РРЦ в тенге'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='supplier_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена поставщика'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_ptr', to='core.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_ptr', to='core.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sp_currency_ptr', to='core.currency', verbose_name='Валюта'),
        ),
        migrations.CreateModel(
            name='PriceManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                ('source', models.CharField(choices=[('rmp_kzt', 'РРЦ в тенге'), ('prime_cost', 'Себестоимость'), ('wholesale_price', 'Оптовая цена'), ('basic_price', 'Базовая цена')], verbose_name='От какой цены считать')),
                ('dest', models.CharField(choices=[('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('rmp', 'РРЦ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], verbose_name='Какую цену считать')),
                ('price_from', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена от')),
                ('price_to', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена до')),
                ('markup', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Накрутка')),
                ('increase', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Надбавка')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_category_ptr', to='core.category', verbose_name='Категория')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_supplier_ptr', to='core.supplier', verbose_name='Поставщик')),
            ],
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='price_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_price_manager_ptr', to='core.pricemanager', verbose_name='Наценка'),
        ),
    ]
