# Generated by Django 5.2.5 on 2025-08-25 10:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension




class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mainproduct_supplier'),
    ]

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
        migrations.AddField(
            model_name='mainproduct',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='mainproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='core_mainpr_search__c63117_gin'),
        )
    ]
