# Generated by Django 5.2.5 on 2025-08-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_mainproduct_rmp_kzt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(verbose_name='Название'),
        ),
    ]
