# Generated by Django 5.2.5 on 2025-08-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_mainproduct_search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='sku',
            field=models.CharField(blank=True, null=True, verbose_name='Артикул товара'),
        ),
    ]
