# Generated by Django 5.2.5 on 2025-08-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemanager',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pm_category_ptr', to='core.category', verbose_name='Категория'),
        ),
    ]
