# Generated by Django 5.2.5 on 2025-08-25 11:09

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_mainproduct_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(auto_created=True, editable=False, null=True),
        ),
    ]
