# Generated by Django 5.2.5 on 2026-09-23 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_shoppingtabexport_notification_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitrix24Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_user_id', models.PositiveBigIntegerField(unique=True, verbose_name='ID в Bitrix24')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Привязан')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitrix24_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аккаунт Bitrix24',
                'verbose_name_plural': 'Аккаунты Bitrix24',
            },
        ),
    ]
