# Generated by Django 5.2.5 on 2026-09-24 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bitrix24account'),
        ('product', '0011_productsetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='source_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exploded_cart_items', to='product.product', verbose_name='Из набора'),
        ),
    ]
