# Generated by Django 5.2.5 on 2025-08-17 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_pricemanager_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricemanager',
            name='increase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Надбавка'),
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='price_from',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена от'),
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='price_to',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена до'),
        ),
    ]
