# Generated by Django 5.2.5 on 2025-08-26 03:33

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_mainproduct_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Вектор поиска'),
        ),
    ]
