# Generated by Django 5.2.5 on 2025-08-17 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pricemanager_increase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturerdict',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='md_manufacturer_ptr', to='core.manufacturer', verbose_name='Производитель'),
        ),
    ]
