# Generated by Django 5.2.5 on 2025-09-01 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_mainproduct_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproduct',
            name='rmp',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='id_as_sku',
        ),
        migrations.AddField(
            model_name='setting',
            name='differ_by_name',
            field=models.BooleanField(default=True, verbose_name='Различать по имени'),
        ),
        migrations.AddField(
            model_name='setting',
            name='update_main',
            field=models.BooleanField(default=True, verbose_name='Обновлять главный прайс'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'xlsm'])], verbose_name='Файл'),
        ),
    ]
