# Generated by Django 5.2.5 on 2025-08-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_mainproduct_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproduct',
            name='rmp',
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='source',
            field=models.CharField(choices=[('rmp_kzt', 'РРЦ поставщика в тенге'), ('supplier_price_kzt', 'Цена поставщика в тенге'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], verbose_name='От какой цены считать'),
        ),
    ]
