# Generated by Django 5.2.4 on 2025-09-02 10:46

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_mainproduct_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_price_upload_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки цен'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='last_stock_upload_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки остатков'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'xlsm'])], verbose_name='Файл'),
        ),
    ]
