# Generated by Django 5.2.5 on 2025-09-01 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_mainproduct_rmp_remove_setting_id_as_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='differ_by_name',
        ),
    ]
