# Generated by Django 5.2.5 on 2025-08-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_manufacturerdict_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='source',
            field=models.CharField(choices=[('rmp_kzt', 'РРЦ в тенге (поставщика)'), ('supplier_price', 'Цена поставщика'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('rmp', 'РРЦ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], verbose_name='От какой цены считать'),
        ),
    ]
