# Generated by Django 5.2.5 on 2025-09-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_setting_differ_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='differ_by_name',
            field=models.BooleanField(default=True, verbose_name='Различать по имени'),
        ),
    ]
