# Generated by Django 5.2.5 on 2025-08-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_updated_at_alter_pricemanager_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('category', 'Категория'), ('manufacturer', 'Производитель'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика'), ('rmp_raw', 'РРЦ в валюте закупа'), ('rmp_kzt', 'РРЦ в тенге')]),
        ),
    ]
