# Generated by Django 5.2.5 on 2025-08-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20250814_1237'),
        ('core', '0015_mainproduct_depth_mainproduct_length_and_more'),
    ]

    operations = [
    ]
