# Generated by Django 5.2.5 on 2025-09-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_setting_differ_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='discounts',
            field=models.ManyToManyField(related_name='suppliers', to='core.discount'),
        ),
    ]
