# Generated by Django 5.2.5 on 2025-08-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mainproduct_depth_mainproduct_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='price_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_price_manager_ptr', to='core.pricemanager', verbose_name='Наценка'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Вес'),
        ),
    ]
