# Generated by Django 5.2.5 on 2025-08-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20250818_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(verbose_name='Название'),
        ),
    ]
