# Generated by Django 5.2.5 on 2025-09-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_supplier_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='delivery_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Срок доставки'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='core.discount'),
        ),
    ]
