# Generated by Django 5.2.5 on 2025-08-20 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_product_manufacturer'),
        ('core', '0017_alter_product_name'),
    ]

    operations = [
    ]
