# Generated by Django 5.2.5 on 2025-09-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_supplier_delivery_days_alter_supplier_discounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproduct',
            name='stock',
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Наличие'),
        ),
    ]
