# Generated by Django 5.2.5 on 2025-09-06 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_mainproduct_stock_mainproduct_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='mainproduct',
            name='price_manager',
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_product', to='core.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_product', to='core.mainproduct', verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_product', to='core.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_product', to='core.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='price_manager',
            field=models.ManyToManyField(blank=True, null=True, related_name='main_products', to='core.pricemanager', verbose_name='Наценка'),
        ),
    ]
