# Generated by Django 5.2.5 on 2025-09-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_mainproduct_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricemanager',
            name='supplier',
        ),
        migrations.AddField(
            model_name='pricemanager',
            name='suppliers',
            field=models.ManyToManyField(related_name='price_managers', to='core.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='price_manager',
            field=models.ManyToManyField(blank=True, related_name='main_products', to='core.pricemanager', verbose_name='Наценка'),
        ),
    ]
