# Generated by Django 5.2.5 on 2025-09-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_pricemanager_supplier_pricemanager_suppliers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricemanager',
            name='discount',
        ),
        migrations.AddField(
            model_name='pricemanager',
            name='discounts',
            field=models.ManyToManyField(related_name='price_managers', to='core.discount', verbose_name='Группа скидок'),
        ),
    ]
