# Generated by Django 5.2.5 on 2025-09-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_pricemanager_discount_pricemanager_discounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricemanager',
            name='discounts',
        ),
        migrations.AddField(
            model_name='pricemanager',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_managers', to='core.discount', verbose_name='Группа скидок'),
        ),
    ]
