# Generated by Django 5.2.5 on 2025-09-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_pricemanager_discounts_pricemanager_discount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='parent_child_constraint'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('setting', 'key'), name='product-field-constraint'),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('name', 'supplier'), name='name_supplier_constraint'),
        ),
    ]
