# Generated by Django 5.2.5 on 2025-09-08 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_category_parent_child_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricemanager',
            name='suppliers',
        ),
        migrations.AddField(
            model_name='pricemanager',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_managers', to='core.supplier', verbose_name='Поставщик'),
        ),
    ]
