# Generated by Django 5.2.5 on 2025-09-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_pricemanager_suppliers_pricemanager_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='stock',
            field=models.PositiveIntegerField(null=True, verbose_name='Остаток'),
        ),
    ]
