# Generated by Django 5.2.5 on 2025-09-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_mainproduct_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='rmp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РРЦ(Не используется)'),
        ),
    ]
