# Generated by Django 5.2.5 on 2025-09-08 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_mainproduct_rmp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='discounts',
        ),
        migrations.AddField(
            model_name='discount',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.supplier', verbose_name='Поставщик'),
            preserve_default=False,
        ),
    ]
