# Generated by Django 5.2.5 on 2025-09-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_supplier_discounts_discount_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(fields=('name', 'supplier'), name='discount_name_supplier_constraint'),
        ),
    ]
