# Generated by Django 5.2.5 on 2025-09-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_discount_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproduct',
            name='rmp',
        ),
        migrations.RemoveField(
            model_name='mainproduct',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='price_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление цены'),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='stock_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление остатка'),
        ),
    ]
