# Generated by Django 5.2.5 on 2025-09-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_mainproduct_rmp_remove_mainproduct_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainproduct',
            old_name='price_manager',
            new_name='price_managers',
        ),
    ]
