# Generated by Django 5.2.5 on 2025-09-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_price_manager_mainproduct_price_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproduct',
            name='currency',
        ),
    ]
