# Generated by Django 5.2.5 on 2025-09-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_supplierproduct_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='rmp_kzt',
            new_name='rmp',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='rmp_raw',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='supplier_price_kzt',
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена поставщика в тенге'),
        ),
    ]
