# Generated by Django 5.2.5 on 2025-09-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_rmp_kzt_supplierproduct_rmp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('category', 'Категория'), ('discount', 'Группа скидок'), ('manufacturer', 'Производитель'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика в указанной валюте'), ('rmp', 'РРЦ в указанной валюте')]),
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='source',
            field=models.CharField(choices=[('rmp', 'РРЦ в тенге'), ('supplier_price', 'Цена поставщика в тенге'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('rmp', 'РРЦ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], verbose_name='От какой цены считать'),
        ),
    ]
