# Generated by Django 5.2.5 on 2025-09-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_link_key_alter_pricemanager_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricemanager',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='discount',
        ),
        migrations.AddField(
            model_name='pricemanager',
            name='discounts',
            field=models.ManyToManyField(related_name='price_managers', to='core.discount', verbose_name='Группа скидок'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='discounts',
            field=models.ManyToManyField(related_name='products', to='core.discount', verbose_name='Группа скидок'),
        ),
    ]
