# Generated by Django 5.2.5 on 2025-09-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_pricemanager_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='price_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление цены'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='stock_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление остатка'),
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('category', 'Категория'), ('discounts', 'Группа скидок'), ('manufacturer', 'Производитель'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика в указанной валюте'), ('rmp', 'РРЦ в указанной валюте')]),
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='price_managers', to='core.discount', verbose_name='Группа скидок'),
        ),
    ]
