# Generated by Django 5.2.5 on 2025-09-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_supplier_price_updated_at_supplier_stock_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='price_updated_at',
            field=models.DateTimeField(verbose_name='Последнее обновление цены'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='stock_updated_at',
            field=models.DateTimeField(verbose_name='Последнее обновление остатка'),
        ),
    ]
