# Generated by Django 5.2.4 on 2025-09-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_supplier_price_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='price_updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Последнее обновление цены'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='stock_updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Последнее обновление остатка'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='price_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление цены'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='stock_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление остатка'),
        ),
    ]
