# Generated by Django 5.2.5 on 2025-09-30 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_mainproduct_price_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('main_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_products', to='core.mainproduct', verbose_name='Главный продукт')),
            ],
        ),
        migrations.CreateModel(
            name='ShopingTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('open', models.BooleanField(default=True, verbose_name='Открыта')),
                ('products', models.ManyToManyField(related_name='shoping_tabs', to='core.alternateproduct', verbose_name='Товары')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoping_tabs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
            },
        ),
        migrations.AddConstraint(
            model_name='alternateproduct',
            constraint=models.UniqueConstraint(fields=('name', 'main_product'), name='name_main_product_constraint'),
        ),
        migrations.AddConstraint(
            model_name='shopingtab',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='user_name_constraint'),
        ),
    ]
