# Generated by Django 5.2.5 on 2025-10-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alternateproduct_shopingtab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricemanager',
            name='has_rrp',
            field=models.BooleanField(blank=True, choices=[(None, 'Без разницы'), (True, 'Да'), (False, 'Нет')], null=True, verbose_name='Есть РРЦ'),
        ),
    ]
