# Generated by Django 5.2.5 on 2025-10-06 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_pricemanager_has_rrp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproduct',
            name='available',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='rmp',
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта поставщика'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='rrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='РРЦ в валюте поставщика'),
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('category', 'Категория'), ('discounts', 'Группа скидок'), ('manufacturer', 'Производитель'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика в указанной валюте'), ('rrp', 'РРЦ в указанной валюте')]),
        ),
        migrations.AlterField(
            model_name='pricemanager',
            name='source',
            field=models.CharField(choices=[('rrp', 'РРЦ в валюте поставщика'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], verbose_name='От какой цены считать'),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена поставщика в валюте поставщика'),
        ),
    ]
