# Generated by Django 5.2.5 on 2025-10-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_mainproduct_available_remove_setting_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='price_update_rate',
            field=models.CharField(choices=[('Каждый день', 'Каждый день'), ('Каждую неделю', 'Каждую неделю'), ('Каждые три недели', 'Каждые три недели')], default='Каждый день', verbose_name='Частота обновления цен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='stock_update_rate',
            field=models.CharField(choices=[('Каждый день', 'Каждый день'), ('Каждую неделю', 'Каждую неделю'), ('Каждые три недели', 'Каждые три недели')], default='Каждый день', verbose_name='Частота обновления остатков'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.CharField(choices=[('', 'Не включать'), ('article', 'Артикул поставщика'), ('name', 'Название'), ('category', 'Категория'), ('discounts', 'Группа скидок'), ('manufacturer', 'Производитель'), ('stock', 'Остаток'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('rrp', 'РРЦ в валюте поставщика')]),
        ),
    ]
