# Generated by Django 5.2.5 on 2025-12-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_supplier_price_update_rate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
