# Generated by Django 5.2.5 on 2025-10-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_supplier_price_update_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopingtab',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='shopingtab',
            name='products',
            field=models.ManyToManyField(related_name='shoping_tabs', to='core.mainproduct', verbose_name='Товары'),
        ),
        migrations.DeleteModel(
            name='AlternateProduct',
        ),
    ]
