# Generated by Django 5.2.7 on 2025-10-20 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_shopingtab_quantity_alter_shopingtab_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopingtab",
            name="quantity",
        ),
        migrations.CreateModel(
            name="ShoppingTabItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_items",
                        to="core.mainproduct",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "shopping_tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.shopingtab",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заявки",
                "verbose_name_plural": "Позиции заявки",
            },
        ),
        migrations.AlterField(
            model_name="shopingtab",
            name="products",
            field=models.ManyToManyField(
                related_name="shoping_tabs",
                through="core.ShoppingTabItem",
                to="core.mainproduct",
                verbose_name="Товары",
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingtabitem",
            constraint=models.UniqueConstraint(
                fields=("shopping_tab", "product"), name="shopping_tab_product_unique"
            ),
        ),
    ]
