# Generated by Django 5.2.7 on 2025-10-20 11:25

import django.db.models.deletion
from django.db import migrations, models


def forwards_migrate_products(apps, schema_editor):
    ShopingTab = apps.get_model("core", "ShopingTab")
    ShoppingTabItem = apps.get_model("core", "ShoppingTabItem")

    db_alias = schema_editor.connection.alias

    for tab in ShopingTab.objects.using(db_alias).all():
        try:
            quantity = getattr(tab, "quantity", 1) or 1
        except AttributeError:
            quantity = 1

        legacy_manager = getattr(tab, "legacy_products", None)
        if legacy_manager is None:
            continue

        products = list(legacy_manager.using(db_alias).all())
        for product in products:
            ShoppingTabItem.objects.using(db_alias).get_or_create(
                shopping_tab=tab,
                product=product,
                defaults={"quantity": quantity},
            )


def backwards_migrate_products(apps, schema_editor):
    ShopingTab = apps.get_model("core", "ShopingTab")
    ShoppingTabItem = apps.get_model("core", "ShoppingTabItem")

    db_alias = schema_editor.connection.alias

    for tab in ShopingTab.objects.using(db_alias).all():
        legacy_manager = getattr(tab, "legacy_products", None)
        if legacy_manager is None:
            continue

        items = ShoppingTabItem.objects.using(db_alias).filter(shopping_tab=tab)
        total_quantity = 0
        manager = legacy_manager.using(db_alias)
        for item in items:
            manager.add(item.product)
            total_quantity += item.quantity or 0

        if hasattr(tab, "quantity"):
            tab.quantity = total_quantity or 1
            tab.save(update_fields=["quantity"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_shopingtab_quantity_alter_shopingtab_products_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingTabItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Количество"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_items",
                        to="core.mainproduct",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "shopping_tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.shopingtab",
                        verbose_name="Заявка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заявки",
                "verbose_name_plural": "Позиции заявки",
            },
        ),
        migrations.RenameField(
            model_name="shopingtab",
            old_name="products",
            new_name="legacy_products",
        ),
        migrations.AddField(
            model_name="shopingtab",
            name="products",
            field=models.ManyToManyField(
                related_name="shoping_tabs",
                through="core.ShoppingTabItem",
                to="core.mainproduct",
                verbose_name="Товары",
            ),
        ),
        migrations.RunPython(forwards_migrate_products, backwards_migrate_products),
        migrations.RemoveField(
            model_name="shopingtab",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="shopingtab",
            name="legacy_products",
        ),
        migrations.AddConstraint(
            model_name="shoppingtabitem",
            constraint=models.UniqueConstraint(
                fields=("shopping_tab", "product"), name="shopping_tab_product_unique"
            ),
        ),
    ]
