# Generated by Django 5.2.5 on 2025-12-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_link_setting_remove_setting_supplier_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Category',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Category',
                    table='supplier_manager_category',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Currency',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Currency',
                    table='supplier_manager_currency',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Discount',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Discount',
                    table='supplier_manager_discount',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='MainProduct',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='MainProduct',
                    table='main_product_manager_mainproduct',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Manufacturer',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Manufacturer',
                    table='supplier_manager_manufacturer',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='ManufacturerDict',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='ManufacturerDict',
                    table='supplier_manager_manufacturerdict',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='PriceManager',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='PriceManager',
                    table='product_price_manager_pricemanager',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Supplier',
                ),
            ],
            database_operations=[
                migrations.AlterModelTable(
                    name='Supplier',
                    table='supplier_manager_supplier',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='alternateproduct',
                    name='main_product',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_products', to='main_product_manager.mainproduct', verbose_name='Главный продукт'),
                ),
            ],
            database_operations=[
            ],
        ),
    ]
