# Generated by Django 5.2.5 on 2025-12-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_mainproduct_category_remove_supplier_currency_and_more'),
        ('main_product_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternateproduct',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_products', to='main_product_manager.mainproduct', verbose_name='Главный продукт'),
        ),
    ]
