# Generated by Django 5.2.8 on 2025-11-17 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main_price", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="Название")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=1000, verbose_name="Тенге"
                    ),
                ),
            ],
            options={
                "verbose_name": "Валюта",
                "verbose_name_plural": "Валюты",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="Поставщик")),
                (
                    "price_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее обновление цены"
                    ),
                ),
                (
                    "stock_updated_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Последнее обновление остатка",
                    ),
                ),
                (
                    "delivery_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Срок доставки"
                    ),
                ),
                (
                    "price_update_rate",
                    models.CharField(
                        choices=[
                            ("Каждый день", "Каждый день"),
                            ("Каждую неделю", "Каждую неделю"),
                            ("Каждые три недели", "Каждые три недели"),
                        ],
                        verbose_name="Частота обновления цен",
                    ),
                ),
                (
                    "stock_update_rate",
                    models.CharField(
                        choices=[
                            ("Каждый день", "Каждый день"),
                            ("Каждую неделю", "Каждую неделю"),
                            ("Каждые три недели", "Каждые три недели"),
                        ],
                        verbose_name="Частота обновления остатков",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="supplier_manager.currency",
                        verbose_name="Валюта поставщика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название")),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="supplier_manager.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Скидка",
                "verbose_name_plural": "Скидки",
            },
        ),
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article", models.CharField(verbose_name="Артикул поставщика")),
                ("name", models.CharField(verbose_name="Название")),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="Остаток"),
                ),
                (
                    "supplier_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Цена поставщика в валюте поставщика",
                    ),
                ),
                (
                    "rrp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="РРЦ в валюте поставщика",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_price.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "discounts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="supplier_manager.discount",
                        verbose_name="Группа скидок",
                    ),
                ),
                (
                    "main_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_product",
                        to="main_price.mainproduct",
                        verbose_name="Главный продукт",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_product",
                        to="main_price.manufacturer",
                        verbose_name="Производитель",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_products",
                        to="supplier_manager.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар поставщика",
                "verbose_name_plural": "Товары поставщиков",
            },
        ),
        migrations.AddConstraint(
            model_name="discount",
            constraint=models.UniqueConstraint(
                fields=("name", "supplier"), name="discount_name_supplier_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierproduct",
            constraint=models.UniqueConstraint(
                fields=("supplier", "article", "name"),
                name="sp_uniqe_supplier_article_name",
            ),
        ),
    ]
