# Generated by Django 5.2.5 on 2025-12-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0046_remove_mainproduct_category_remove_supplier_currency_and_more')
    ]

    operations = [
        
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Currency',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(unique=True, verbose_name='Название')),
                        ('value', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Тенге')),
                    ],
                ),
            ],
            database_operations=[
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Manufacturer',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(unique=True, verbose_name='Производитель')),
                    ],
                    options={
                        'verbose_name': 'Производитель',
                    },
                ),
            ],
            database_operations=[
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ManufacturerDict',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(unique=True, verbose_name='Вариация')),
                        ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='md_manufacturer_ptr', to='supplier_manager.manufacturer', verbose_name='Производитель')),
                    ],
                    options={
                        'verbose_name': 'Словарь Производителя',
                    },
                ),
            ],
            database_operations=[
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Supplier',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(unique=True, verbose_name='Поставщик')),
                        ('price_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление цены')),
                        ('stock_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление остатка')),
                        ('delivery_days', models.PositiveIntegerField(default=0, verbose_name='Срок доставки')),
                        ('price_update_rate', models.CharField(choices=[('Каждый день', 'Каждый день'), ('Каждую неделю', 'Каждую неделю'), ('Каждые три недели', 'Каждые три недели')], verbose_name='Частота обновления цен')),
                        ('stock_update_rate', models.CharField(choices=[('Каждый день', 'Каждый день'), ('Каждую неделю', 'Каждую неделю'), ('Каждые три недели', 'Каждые три недели')], verbose_name='Частота обновления остатков')),
                        ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='supplier_manager.currency', verbose_name='Валюта поставщика')),
                    ],
                    options={
                        'verbose_name': 'Поставщик',
                    },
                ),
            ],
            database_operations=[
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Category',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(verbose_name='Название')),
                        ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier_manager.category', verbose_name='Подкатегория для')),
                    ],
                    options={
                        'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='parent_child_constraint')],
                    },
                ),
            ],
            database_operations=[
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Discount',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(verbose_name='Название')),
                        ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='supplier_manager.supplier', verbose_name='Поставщик')),
                    ],
                    options={
                        'constraints': [models.UniqueConstraint(fields=('name', 'supplier'), name='discount_name_supplier_constraint')],
                    },
                ),
            ],
            database_operations=[
            ],
        ),
    ]
