# Generated by Django 5.2.5 on 2026-03-19 10:29

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models

def create_kzt(apps, schema_editor):
    # Get the historical model (not the current one)
    Currency = apps.get_model('supplier_manager', 'Currency')
    
    # Your Python code here
    Currency.objects.get_or_create(name='KZT', value=1)


def delete_kzt(apps, schema_editor):
    # Get the historical model (not the current one)
    Currency = apps.get_model('supplier_manager', 'Currency')
    
    # Your Python code here
    Currency.objects.get(name='KZT').delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                ('value', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Тенге')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Вариация')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='md_manufacturer_ptr', to='supplier_manager.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Словарь Производителя',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True, verbose_name='Поставщик')),
                ('price_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление цены')),
                ('stock_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление остатка')),
                ('delivery_days_available', models.PositiveIntegerField(null=True, verbose_name='Срок поставки (Рабочие дни) при наличии')),
                ('delivery_days_navailable', models.PositiveIntegerField(null=True, verbose_name='Срок поставки (Рабочие дни) при отсутствии')),
                ('price_update_rate', models.CharField(choices=[('', ''), ('Каждый день', 'Каждый день'), ('Каждую неделю', 'Каждую неделю'), ('Каждые три недели', 'Каждые три недели')], verbose_name='Частота обновления цен')),
                ('stock_update_rate', models.CharField(choices=[('', ''), ('Каждый день', 'Каждый день'), ('Каждую неделю', 'Каждую неделю'), ('Каждые три недели', 'Каждые три недели')], verbose_name='Частота обновления остатков')),
                ('msg_available', models.CharField(default='Есть в наличии', verbose_name='Сообщение при наличии')),
                ('msg_navailable', models.CharField(default='Нет в наличии', verbose_name='Сообщение при отсутствии')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='supplier_manager.currency', verbose_name='Валюта поставщика')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='supplier_manager.category', verbose_name='Подкатегория для')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='parent_child_constraint')],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='supplier_manager.supplier', verbose_name='Поставщик')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'supplier'), name='discount_name_supplier_constraint')],
            },
        ),
        migrations.RunPython(create_kzt, delete_kzt),
    ]
