# Generated by Django 5.2.5 on 2026-08-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='pim_id',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Id для системы Pim'),
        ),
    ]
