# Generated by Django 5.2.5 on 2025-12-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='msg_available',
            field=models.CharField(default='Есть в наличии', verbose_name='Сообщение при наличии'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='msg_navailable',
            field=models.CharField(default='Нет в наличии', verbose_name='Сообщение при отсутствии'),
        ),
    ]
