# Generated by Django 5.2.5 on 2026-08-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0002_supplier_pim_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='sku_type',
            field=models.CharField(blank=True, choices=[(None, 'Отсутсвует'), ('prefix', 'Префикс'), ('suffix', 'Суффикс')], null=True, verbose_name='Префикс/Суффикс'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sku_value',
            field=models.CharField(blank=True, null=True, verbose_name='Значение Префикса/Суффикса'),
        ),
    ]
