# Generated by Django 5.2.5 on 2026-01-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0003_category_level_category_lft_category_rght_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Поставщик'},
        ),
    ]
