# Generated by Django 5.2.5 on 2026-08-16 11:54

import django.db.models.deletion
import supplier_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0003_supplier_sku_type_supplier_sku_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='currency',
            field=models.ForeignKey(default=supplier_manager.models._get_default_currnecy, on_delete=django.db.models.deletion.PROTECT, to='supplier_manager.currency', verbose_name='Валюта поставщика'),
        ),
    ]
