# Generated by Django 5.2.5 on 2026-08-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0004_alter_supplier_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pim_id',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Id для системы Pim'),
        ),
    ]
