# Generated by Django 5.2.5 on 2026-02-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0004_alter_supplier_options'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='supplier',
                    name='grouping_priority',
                    field=models.PositiveIntegerField(default=0, verbose_name='Приоритет группы'),
                ),
            ],
            # Table already exists. See core\migrations\0045_remove_link_setting_remove_setting_supplier_and_more.py
            database_operations=[
                
            ],
        ),
    ]
