# Generated by Django 5.2.5 on 2026-02-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0005_supplier_grouping_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='grouping_priority',
        ),
    ]
