# Generated by Django 5.2.5 on 2026-02-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0005_supplier_grouping_priority'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='supplier',
                    name='grouping_priority',
                ),
            ],
            # Column was never added at the DB level in 0005 (state-only migration),
            # so there is nothing to remove physically from the database.
            database_operations=[],
        ),
    ]
