# Generated by Django 5.2.5 on 2026-08-18 06:32

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0005_category_pim_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='supplier_manager.category', verbose_name='Подкатегория для'),
        ),
    ]
