# Generated by Django 5.2.5 on 2026-02-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0007_supplier_delivery_days_stock_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='delivery_days',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_days_available',
            field=models.PositiveIntegerField(null=True, verbose_name='Срок поставки (Рабочие дни) при наличии'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='delivery_days_navailable',
            field=models.PositiveIntegerField(null=True, verbose_name='Срок поставки (Рабочие дни) при отсутствии'),
        ),
    ]
