# Generated by Django 5.2.5 on 2026-02-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0008_remove_supplier_delivery_days_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='supplier',
                    name='grouping_priority',
                    field=models.IntegerField(null=True),
                ),
            ],
            # Column was never added at the DB level in 0005 (state-only migration),
            # so there is nothing to remove physically from the database.
            database_operations=[],
        ),
    ]
