# Generated by Django 5.2.5 on 2026-08-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0008_manufacturer_pim_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tree_id', 'lft'], name='supplier_manager_category_afbf'),
        ),
    ]
