# Generated by Django 5.2.5 on 2026-02-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0009_supplier_grouping_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='price_update_rate',
            field=models.CharField(choices=[('', ''), ('Каждый день', 'Каждый день'), ('Каждую неделю', 'Каждую неделю'), ('Каждые три недели', 'Каждые три недели')], verbose_name='Частота обновления цен'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='stock_update_rate',
            field=models.CharField(choices=[('', ''), ('Каждый день', 'Каждый день'), ('Каждую неделю', 'Каждую неделю'), ('Каждые три недели', 'Каждые три недели')], verbose_name='Частота обновления остатков'),
        ),
    ]
