# Generated by Django 5.2.5 on 2026-09-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0009_category_supplier_manager_category_afbf'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='price_priority',
            field=models.PositiveIntegerField(blank=True, help_text='Меньше — выше приоритет. Пусто — поставщик не проранжирован.', null=True, verbose_name='Приоритет по цене'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='stock_priority',
            field=models.PositiveIntegerField(blank=True, help_text='Меньше — выше приоритет. Пусто — поставщик не проранжирован.', null=True, verbose_name='Приоритет по остаткам'),
        ),
    ]
