# Generated by Django 5.2.12 on 2026-03-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0010_remove_supplier_grouping_priority_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=[
                migrations.RemoveField(
                    model_name='supplier',
                    name='grouping_priority',
                ),
            ],
        )
    ]
