# Generated by Django 5.2.5 on 2026-10-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_manager', '0014_supplier_priority_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_unsupplied',
            field=models.BooleanField(default=False, editable=False, verbose_name='Без поставщика'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_unsupplied', True)), fields=('is_unsupplied',), name='supplier_single_unsupplied'),
        ),
    ]
