# Generated by Django 5.2.5 on 2026-09-23 10:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z][0-9A-Za-z._-]*$', 'Только латиница, цифры, точка, дефис и подчёркивание — например, 1.4.0.')], verbose_name='Версия')),
                ('title', models.CharField(blank=True, help_text='Необязательно. Например: «Приоритеты поставщиков».', max_length=200, verbose_name='Заголовок')),
                ('summary', models.TextField(help_text='Пара предложений. Приходит всем пользователям в «Оповещения».', verbose_name='Кратко')),
                ('article_html', models.TextField(help_text='Что изменилось с точки зрения менеджера: как это влияет на работу и на что обратить внимание. Скрипты, стили и обработчики событий вырезаются при сохранении.', verbose_name='Статья (HTML)')),
                ('article_markdown', models.TextField(blank=True, editable=False, verbose_name='Статья (Markdown)')),
                ('released_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата выхода')),
                ('is_published', models.BooleanField(default=False, help_text='При публикации краткое описание рассылается всем пользователям — один раз.', verbose_name='Опубликовано')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Оповещение отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
                'ordering': ('-released_at', '-pk'),
            },
        ),
    ]
