# Generated by Django 5.2.8 on 2025-11-17 10:29

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="Производитель")),
            ],
            options={
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
            },
        ),
        migrations.CreateModel(
            name="ManufacturerDict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="Вариация")),
            ],
            options={
                "verbose_name": "Словарь Производителя",
                "verbose_name_plural": "Словари Производителей",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main_price.category",
                        verbose_name="Подкатегория для",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="MainProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True, null=True, verbose_name="Артикул товара"
                    ),
                ),
                ("article", models.CharField(verbose_name="Артикул поставщика")),
                ("name", models.CharField(verbose_name="Название")),
                (
                    "stock",
                    models.PositiveIntegerField(null=True, verbose_name="Остаток"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=1, default=0, max_digits=8, verbose_name="Вес"
                    ),
                ),
                (
                    "prime_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Себестоимость",
                    ),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Оптовая цена",
                    ),
                ),
                (
                    "basic_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Базовая цена",
                    ),
                ),
                (
                    "m_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Цена ИМ",
                    ),
                ),
                (
                    "wholesale_price_extra",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Оптовая цена доп.",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Длина"
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ширина",
                    ),
                ),
                (
                    "depth",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Глубина",
                    ),
                ),
                (
                    "price_updated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Последнее обновление цены"
                    ),
                ),
                (
                    "stock_updated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Последнее обновление остатка"
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True, verbose_name="Вектор поиска"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_price.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Главный товар",
                "verbose_name_plural": "Главный прайс",
            },
        ),
    ]
