# Generated by Django 5.2.8 on 2025-11-17 10:29

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main_price", "0001_initial"),
        ("price_manager", "0001_initial"),
        ("supplier_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainproduct",
            name="price_managers",
            field=models.ManyToManyField(
                blank=True,
                related_name="main_products",
                to="price_manager.pricemanager",
                verbose_name="Наценка",
            ),
        ),
        migrations.AddField(
            model_name="mainproduct",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mp_supplier_ptr",
                to="supplier_manager.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="mainproduct",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mp_manufacturer_ptr",
                to="main_price.manufacturer",
                verbose_name="Производитель",
            ),
        ),
        migrations.AddField(
            model_name="manufacturerdict",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="md_manufacturer_ptr",
                to="main_price.manufacturer",
                verbose_name="Производитель",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"), name="parent_child_constraint"
            ),
        ),
        migrations.AddIndex(
            model_name="mainproduct",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="main_price__search__b2cae9_gin"
            ),
        ),
    ]
