# Generated by Django 5.2.5 on 2026-03-21 07:02

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, null=True, verbose_name='Артикул товара')),
                ('article', models.CharField(verbose_name='Артикул поставщика')),
                ('name', models.CharField(verbose_name='Название')),
                ('stock', models.PositiveIntegerField(null=True, verbose_name='Остаток')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=8, null=True, verbose_name='Вес')),
                ('prime_cost', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Себестоимость')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Оптовая цена')),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Базовая цена')),
                ('m_price', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Цена ИМ')),
                ('wholesale_price_extra', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Оптовая цена доп.')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Цена со скидкой')),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Длина')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ширина')),
                ('depth', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Глубина')),
                ('price_updated_at', models.DateTimeField(null=True, verbose_name='Последнее обновление цены')),
                ('stock_updated_at', models.DateTimeField(null=True, verbose_name='Последнее обновление остатка')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Вектор поиска')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainproducts', to='supplier_manager.category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_manufacturer_ptr', to='supplier_manager.manufacturer', verbose_name='Производитель')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_products', to='supplier_manager.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Главный продукт',
                'ordering': ['article', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MainProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Цена')),
                ('price_type', models.CharField(choices=[(None, '----'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], null=True, verbose_name='Тип цены')),
                ('stock', models.PositiveIntegerField(null=True, verbose_name='Остаток')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_log', to='main_product_manager.mainproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изменения Главных продуктов',
                'ordering': ['-update_time'],
            },
        ),
        migrations.AddIndex(
            model_name='mainproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='main_produc_search__b370a9_gin'),
        ),
        migrations.AddConstraint(
            model_name='mainproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'article', 'name'), name='mp_unique_supplier_article_name'),
        ),
        migrations.AddConstraint(
            model_name='mainproductlog',
            constraint=models.UniqueConstraint(fields=('update_time', 'main_product'), name='mpl_unique_date_mp'),
        ),
    ]
