# Generated by Django 5.2.5 on 2025-12-02 10:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_price_manager', '0001_initial'),
        ('supplier_manager', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='MainProduct',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('sku', models.CharField(blank=True, null=True, verbose_name='Артикул товара')),
                        ('article', models.CharField(verbose_name='Артикул поставщика')),
                        ('name', models.CharField(verbose_name='Название')),
                        ('stock', models.PositiveIntegerField(null=True, verbose_name='Остаток')),
                        ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Вес')),
                        ('prime_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Себестоимость')),
                        ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Оптовая цена')),
                        ('basic_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Базовая цена')),
                        ('m_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Цена ИМ')),
                        ('wholesale_price_extra', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Оптовая цена доп.')),
                        ('length', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Длина')),
                        ('width', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ширина')),
                        ('depth', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Глубина')),
                        ('price_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Последнее обновление цены')),
                        ('stock_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Последнее обновление остатка')),
                        ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='Вектор поиска')),
                        ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier_manager.category', verbose_name='Категория')),
                        ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_manufacturer_ptr', to='supplier_manager.manufacturer', verbose_name='Производитель')),
                        ('price_managers', models.ManyToManyField(blank=True, related_name='main_products', to='product_price_manager.pricemanager', verbose_name='Наценка')),
                        ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mp_supplier_ptr', to='supplier_manager.supplier', verbose_name='Поставщик')),
                    ],
                    options={
                        'verbose_name': 'Главный продукт',
                        'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='main_produc_search__b370a9_gin')],
                        'constraints': [models.UniqueConstraint(fields=('supplier', 'article', 'name'), name='mp_uniqe_supplier_article_name')],
                    },
                ),
            ],
            database_operations=[
            ],
        ),
    ]
