# Generated by Django 5.2.5 on 2025-12-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0001_initial'),
        ('product_price_manager', '0001_initial'),
        ('supplier_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Цена')),
                ('price_type', models.CharField(choices=[(None, '----'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], null=True, verbose_name='Тип цены')),
                ('stock', models.PositiveIntegerField(null=True, verbose_name='Остаток')),
            ],
            options={
                'verbose_name': 'Изменения Главных продуктов',
            },
        ),
        migrations.RemoveConstraint(
            model_name='mainproduct',
            name='mp_uniqe_supplier_article_name',
        ),
        migrations.AddConstraint(
            model_name='mainproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'article', 'name'), name='mp_unique_supplier_article_name'),
        ),
        migrations.AddField(
            model_name='mainproductlog',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_log', to='main_product_manager.mainproduct', verbose_name='Товар'),
        ),
        migrations.AddConstraint(
            model_name='mainproductlog',
            constraint=models.UniqueConstraint(fields=('update_time', 'main_product'), name='mpl_unique_date_mp'),
        ),
    ]
