# Generated by Django 5.2.5 on 2026-03-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mainproductlog',
            name='mpl_unique_date_mp',
        ),
    ]
