# Generated by Django 5.2.5 on 2025-12-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0002_mainproductlog_and_more'),
        ('product_price_manager', '0002_uniquepricemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='unique_price_manager',
            field=models.ManyToManyField(blank=True, related_name='main_products', to='product_price_manager.uniquepricemanager', verbose_name='Индивидуальные наценки'),
        ),
    ]
