# Generated by Django 5.2.12 on 2026-04-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0002_remove_mainproductlog_mpl_unique_date_mp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainproduct',
            options={'ordering': ['id'], 'verbose_name': 'Главный продукт'},
        ),
    ]
