# Generated by Django 5.2.5 on 2025-12-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0003_mainproduct_unique_price_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainproduct',
            old_name='unique_price_manager',
            new_name='unique_price_managers',
        ),
    ]
