# Generated by Django 5.2.5 on 2026-08-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0003_alter_mainproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='pim_id',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='Id для системы Pim'),
        ),
    ]
