# Generated by Django 5.2.5 on 2025-12-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0004_rename_unique_price_manager_mainproduct_unique_price_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='price_updated_at',
            field=models.DateTimeField(null=True, verbose_name='Последнее обновление цены'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='stock_updated_at',
            field=models.DateTimeField(null=True, verbose_name='Последнее обновление остатка'),
        ),
    ]
