# Generated by Django 5.2.5 on 2025-12-13 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0005_alter_mainproduct_price_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainproduct',
            old_name='unique_price_managers',
            new_name='special_prices',
        ),
    ]
