# Generated by Django 5.2.5 on 2025-12-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0006_rename_unique_price_managers_mainproduct_special_prices'),
        ('product_price_manager', '0004_alter_uniquepricemanager_dest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='special_prices',
            field=models.ManyToManyField(blank=True, related_name='main_products', to='product_price_manager.uniquepricemanager', verbose_name='Спец наценки'),
        ),
    ]
