# Generated by Django 5.2.5 on 2025-12-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0007_alter_mainproduct_special_prices'),
        ('supplier_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_products', to='supplier_manager.supplier', verbose_name='Поставщик'),
        ),
    ]
