# Generated by Django 5.2.5 on 2025-12-30 07:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0008_alter_mainproduct_supplier'),
        ('product_price_manager', '0005_rename_uniquepricemanager_specialprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[(None, 'Фиксированная цена'), ('rrp', 'РРЦ в валюте поставщика'), ('supplier_price', 'Цена поставщика в валюте поставщика'), ('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], null=True, verbose_name='От какой цены считать')),
                ('dest', models.CharField(blank=True, choices=[('basic_price', 'Базовая цена'), ('prime_cost', 'Себестоимость'), ('m_price', 'Цена ИМ'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена1')], null=True, verbose_name='Какую цену считать')),
                ('markup', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Накрутка')),
                ('increase', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Надбавка')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фиксированная цена')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricetags', to='main_product_manager.mainproduct', verbose_name='Товар главного прайса')),
                ('p_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricetags', to='product_price_manager.pricemanager', verbose_name='Менеджер наценок')),
            ],
            options={
                'verbose_name': 'Наценка',
                'verbose_name_plural': 'Наценки',
            },
        ),
    ]
