# Generated by Django 5.2.5 on 2026-09-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0008_remove_mp_unique_supplier_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='kaspi_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Цена Каспи'),
        ),
    ]
