# Generated by Django 5.2.5 on 2026-09-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0009_mainproduct_kaspi_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='pim_id',
            field=models.CharField(blank=True, db_index=True, null=True, verbose_name='Id для системы Pim'),
        ),
    ]
