# Generated by Django 5.2.5 on 2025-12-30 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0009_pricetag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceTag',
        ),
    ]
