# Generated by Django 5.2.5 on 2025-12-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0010_delete_pricetag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproduct',
            name='price_managers',
        ),
        migrations.RemoveField(
            model_name='mainproduct',
            name='special_prices',
        ),
    ]
