# Generated by Django 5.2.5 on 2026-01-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0011_remove_mainproduct_price_managers_and_more'),
        ('supplier_manager', '0002_supplier_msg_available_supplier_msg_navailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainproducts', to='supplier_manager.category', verbose_name='Категория'),
        ),
    ]
