# Generated by Django 5.2.5 on 2026-01-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0012_alter_mainproduct_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainproduct',
            options={'ordering': ['article', 'name'], 'verbose_name': 'Главный продукт'},
        ),
    ]
