# Generated by Django 5.2.5 on 2026-01-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0013_alter_mainproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='basic_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='m_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Цена ИМ'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='prime_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Себестоимость'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=8, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Оптовая цена'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='wholesale_price_extra',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Оптовая цена доп.'),
        ),
    ]
