# Generated by Django 5.2.5 on 2026-10-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0013_mainproduct_is_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='set_delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок поставки набора'),
        ),
    ]
