# Generated by Django 5.2.5 on 2026-02-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0015_alter_mainproductlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainproductlog',
            options={'ordering': ['update_time'], 'verbose_name': 'Изменения Главных продуктов'},
        ),
    ]
