# Generated by Django 5.2.5 on 2026-02-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0016_alter_mainproductlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainproductlog',
            options={'ordering': ['-update_time'], 'verbose_name': 'Изменения Главных продуктов'},
        ),
    ]
