# Generated by Django 5.2.5 on 2026-02-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0017_alter_mainproductlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
