# Generated by Django 5.2.5 on 2026-02-13 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_product_manager', '0018_mainproduct_discount_price'),
        ('supplier_manager', '0009_supplier_grouping_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
