# Generated by Django 5.2.8 on 2025-11-17 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main_price", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternateProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название")),
                (
                    "main_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alternate_products",
                        to="main_price.mainproduct",
                        verbose_name="Главный продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Альтернативный товар",
                "verbose_name_plural": "Альтернативные товары",
            },
        ),
        migrations.CreateModel(
            name="ShopingTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название")),
                ("open", models.BooleanField(default=True, verbose_name="Открыта")),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="shoping_tabs",
                        to="shoping_cart.alternateproduct",
                        verbose_name="Товары",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shoping_tabs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
            },
        ),
        migrations.AddConstraint(
            model_name="alternateproduct",
            constraint=models.UniqueConstraint(
                fields=("name", "main_product"), name="name_main_product_constraint"
            ),
        ),
        migrations.AddConstraint(
            model_name="shopingtab",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="user_name_constraint"
            ),
        ),
    ]
