# Generated by Django 5.2.5 on 2026-01-20 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'xlsm', 'csv'])], verbose_name='Файл'),
        ),
    ]
