# Generated by Django 5.2.5 on 2026-05-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
