"""Build (or check) the knowledge base's README index files.

`.claude/knowledge/` is one directory per app, one markdown file per topic.
Every topic opens with front matter, and that front matter is the only source
of the indexes — nobody edits a README by hand:

    ---
    title: Product sets («наборы»)
    summary: ProductSetItem, sync from PIM, set cost/buildable, UI and export.
    code: price_manager/product/services/sets.py, price_manager/product/set_costs.py
    ---
    # Product sets («наборы»)
    ...

`title` and `summary` are required; `code` is a comma-separated list of repo
paths the topic is about (optional, but it is what lets a reader find the
topic from the code). This script writes `<app>/README.md` for every app
directory and the top-level `README.md`. The glossary, `glossary.md`, is
hand-maintained and only linked.

    python .claude/tools/knowledge_index.py           # rewrite the READMEs
    python .claude/tools/knowledge_index.py --check   # exit 1 if any is stale

`--check` also fails on a topic without front matter and on a stray top-level
`*.md` (a flat `<app>.md` coming back), and on a `[[app]]` or `[[app/topic]]`
link that points nowhere. A `code` path that no longer exists is
reported as a warning only: renaming a file in an unrelated change should not
turn CI red, but the keeper should hear about it. CI runs `--check`.
"""
import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
KNOWLEDGE = REPO_ROOT / '.claude' / 'knowledge'

# Knowledge directory -> keeper agent. Same mapping as the table in CLAUDE.md
# and KEEPERS in .claude/hooks/suggest_record.py (keyed by Django app there).
KEEPERS = {
    'core': 'core-keeper',
    'main_product_manager': 'main-product-keeper',
    'product': 'product-keeper',
    'product_price_manager': 'price-rules-keeper',
    'retiring_stack': 'retiring-stack-keeper',
    'supplier_manager': 'supplier-manager-keeper',
    'supplier_product_manager': 'supplier-product-keeper',
}
APPS_OF = {'retiring_stack': '`pricing`, `supplier`, `supplier_feed`, `dataframe`'}

HAND_WRITTEN = {'README.md', 'glossary.md'}
GENERATED_NOTE = ('<!-- Generated by .claude/tools/knowledge_index.py from the topics\' front matter. '
                  'Do not edit: change the front matter and rerun the script. -->')

INTRO = """\
# Knowledge base

Per-app notes: mechanism, traps and why-it-is-like-this, found by working in
the code. Each app directory is owned by its **keeper agent** — consult the
keeper before working in an app, and record back with `/record-insight <app>`.
Repo-wide invariants live in `CLAUDE.md`, not here; workflow preferences live
in the user's memory, not here.

- **One directory per app, one file per topic.** Each directory has an
  `overview.md`; start there. A topic stays short (~200 lines) — when one
  grows past that, it is split, not extended.
- **Front matter** (`title`, `summary`, `code`) on every topic is the source of
  these indexes. The READMEs are generated: edit front matter and run
  `python .claude/tools/knowledge_index.py`; CI runs it with `--check`.
- **Links:** `[[app]]` means that app's directory, `[[app/topic]]` one topic.
- **[Glossary](glossary.md)** — Russian UI terms ↔ code ↔ PIM. Hand-written.
"""


class TopicError(Exception):
    pass


def read_front_matter(path: Path) -> dict:
    lines = path.read_text(encoding='utf-8').splitlines()
    if not lines or lines[0] != '---' or '---' not in lines[1:]:
        raise TopicError(f'{path.relative_to(REPO_ROOT).as_posix()}: no front matter')
    meta = {}
    for line in lines[1:lines.index('---', 1)]:
        key, sep, value = line.partition(':')
        if sep:
            meta[key.strip()] = value.strip()
    missing = [key for key in ('title', 'summary') if not meta.get(key)]
    if missing:
        raise TopicError(f'{path.relative_to(REPO_ROOT).as_posix()}: front matter lacks {", ".join(missing)}')
    meta['code'] = [part.strip() for part in meta.get('code', '').split(',') if part.strip()]
    return meta


def topics_of(app_dir: Path) -> list[tuple[str, dict]]:
    """(slug, front matter) — overview first, the rest by slug."""
    topics = [(path.stem, read_front_matter(path))
              for path in app_dir.glob('*.md') if path.name != 'README.md']
    return sorted(topics, key=lambda item: (item[0] != 'overview', item[0]))


def cell(text: str) -> str:
    return text.replace('|', '\\|')


def app_readme(app: str, topics) -> str:
    keeper = KEEPERS.get(app, '—')
    rows = [
        f'| [{cell(meta["title"])}]({slug}.md) | {cell(meta["summary"])} | '
        + (', '.join(f'`{path}`' for path in meta['code']) or '—') + ' |'
        for slug, meta in topics
    ]
    apps = f' Covers {APPS_OF[app]}.' if app in APPS_OF else ''
    return '\n'.join([
        GENERATED_NOTE,
        f'# {app} — knowledge',
        '',
        f'Keeper: `{keeper}`.{apps} Start with [overview](overview.md). '
        'Back to the [knowledge base](../README.md) · [glossary](../glossary.md).',
        '',
        '| Topic | What it covers | Code |',
        '|---|---|---|',
        *rows,
        '',
    ])


def root_readme(apps) -> str:
    rows = []
    for app, topics in apps:
        links = ' · '.join(f'[{slug}]({app}/{slug}.md)' for slug, _ in topics)
        rows.append(f'| [{app}]({app}/README.md) | `{KEEPERS.get(app, "—")}` | {links} |')
    return '\n'.join([
        GENERATED_NOTE,
        INTRO,
        '| App | Keeper | Topics |',
        '|---|---|---|',
        *rows,
        '',
    ])


def build() -> tuple[dict[Path, str], list[str], list[str]]:
    """({README path: content}, errors, warnings)."""
    errors, warnings, outputs, apps = [], [], {}, []
    for path in sorted(KNOWLEDGE.glob('*.md')):
        if path.name not in HAND_WRITTEN:
            errors.append(f'{path.relative_to(REPO_ROOT).as_posix()}: topics belong in an app directory')
    if not (KNOWLEDGE / 'glossary.md').exists():
        errors.append('.claude/knowledge/glossary.md is missing')
    for app_dir in sorted(p for p in KNOWLEDGE.iterdir() if p.is_dir()):
        try:
            topics = topics_of(app_dir)
        except TopicError as exc:
            errors.append(str(exc))
            continue
        if not any(slug == 'overview' for slug, _ in topics):
            errors.append(f'{app_dir.relative_to(REPO_ROOT).as_posix()}: no overview.md')
        if app_dir.name not in KEEPERS:
            warnings.append(f'{app_dir.relative_to(REPO_ROOT).as_posix()}: no keeper in KEEPERS')
        for slug, meta in topics:
            for code in meta['code']:
                if not (REPO_ROOT / code).exists():
                    warnings.append(f'{app_dir.name}/{slug}.md: code path {code} does not exist')
        outputs[app_dir / 'README.md'] = app_readme(app_dir.name, topics)
        apps.append((app_dir.name, topics))
    outputs[KNOWLEDGE / 'README.md'] = root_readme(apps)
    errors.extend(broken_links())
    return outputs, errors, warnings


LINK = re.compile(r'\[\[([a-z_]+)(?:/([a-z0-9-]+))?\]\]')


def broken_links() -> list[str]:
    """`[[app]]` must name an app directory, `[[app/topic]]` a topic in it.

    Splitting or renaming a topic is exactly when these break, and nothing else
    would notice — a dead cross-link reads as fine until someone follows it.
    """
    found = []
    for path in sorted(KNOWLEDGE.rglob('*.md')):
        if path.name == 'README.md':
            continue
        for number, line in enumerate(path.read_text(encoding='utf-8').splitlines(), 1):
            for app, topic in LINK.findall(line):
                target = KNOWLEDGE / app / f'{topic}.md' if topic else KNOWLEDGE / app
                if not target.exists():
                    found.append(f'{path.relative_to(REPO_ROOT).as_posix()}:{number}: '
                                 f'broken link [[{app}{"/" + topic if topic else ""}]]')
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--check', action='store_true',
                        help='do not write; exit 1 if a README is stale or a topic is malformed')
    args = parser.parse_args()

    outputs, errors, warnings = build()
    for warning in warnings:
        print(f'warning: {warning}', file=sys.stderr)
    stale = [path for path, content in outputs.items()
             if not path.exists() or path.read_text(encoding='utf-8') != content]
    if args.check:
        for path in stale:
            errors.append(f'{path.relative_to(REPO_ROOT).as_posix()} is stale — run python .claude/tools/knowledge_index.py')
    else:
        for path in stale:
            path.write_text(outputs[path], encoding='utf-8', newline='\n')
            print(f'wrote {path.relative_to(REPO_ROOT).as_posix()}')
    for error in errors:
        print(f'error: {error}', file=sys.stderr)
    return 1 if errors else 0


if __name__ == '__main__':
    sys.exit(main())
