# Generated by Django 5.2.5 on 2026-05-25 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('supplier_sku_column', models.CharField(max_length=128, verbose_name='Колонка артикула поставщика')),
                ('identity_columns', models.JSONField(blank=True, default=list, verbose_name='Identity-колонки')),
                ('variable_columns', models.JSONField(blank=True, default=list, verbose_name='Переменные колонки')),
                ('auto_match_threshold', models.FloatField(default=0.92, verbose_name='Порог авто-матчинга')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_mappings', to='supplier_manager.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Конфигурация выгрузки',
                'verbose_name_plural': 'Конфигурации выгрузок',
                'ordering': ['supplier', 'name'],
            },
        ),
    ]
