# Generated by Django 5.2.5 on 2026-09-02 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataframe', '0001_initial'),
        ('pricing', '0001_initial'),
        ('product', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('supplier_sku_column', models.CharField(max_length=128, verbose_name='Колонка артикула поставщика')),
                ('identity_columns', models.JSONField(blank=True, default=list, verbose_name='Identity-колонки')),
                ('variable_columns', models.JSONField(blank=True, default=list, verbose_name='Переменные колонки')),
                ('auto_match_threshold', models.FloatField(default=0.92, verbose_name='Порог авто-матчинга')),
                ('product_name_column', models.CharField(blank=True, max_length=128, verbose_name='Колонка названия товара')),
                ('product_sku_column', models.CharField(blank=True, max_length=128, verbose_name='Колонка артикула товара')),
                ('dataframe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_mappings', to='dataframe.dataframe', verbose_name='Pipeline')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_mappings', to='supplier.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Конфигурация выгрузки',
                'verbose_name_plural': 'Конфигурации выгрузок',
                'ordering': ['supplier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('processing', 'Обрабатывается'), ('matched', 'Сматчено'), ('partial', 'Частично'), ('done', 'Завершено'), ('error', 'Ошибка')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('session_ids', models.JSONField(default=list, verbose_name='ID сессий файлов')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('feed_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_feeds', to='supplier_feed.feedmapping', verbose_name='Конфигурация')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_feeds', to='supplier.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Сессия выгрузки',
                'verbose_name_plural': 'Сессии выгрузок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=128, verbose_name='Колонка')),
                ('role', models.CharField(choices=[('price', 'Цена'), ('stock', 'Остаток'), ('other', 'Другое')], max_length=16, verbose_name='Роль')),
                ('price_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column_mappings', to='pricing.pricetype', verbose_name='Тип цены')),
                ('feed_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='supplier_feed.feedmapping', verbose_name='Конфигурация выгрузки')),
            ],
            options={
                'verbose_name': 'Маппинг колонки',
                'verbose_name_plural': 'Маппинги колонок',
                'constraints': [models.UniqueConstraint(fields=('feed_mapping', 'column_name'), name='supplier_feed_column_mapping_unique'), models.CheckConstraint(condition=models.Q(models.Q(('role', 'price'), _negated=True), ('price_type__isnull', False), _connector='OR'), name='supplier_feed_column_mapping_price_requires_type')],
            },
        ),
        migrations.CreateModel(
            name='SupplierFeedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(db_index=True, max_length=128, verbose_name='Артикул поставщика')),
                ('data', models.JSONField(default=dict, verbose_name='Данные строки')),
                ('match_candidates', models.JSONField(default=list, verbose_name='Кандидаты на матчинг')),
                ('best_score', models.FloatField(blank=True, null=True, verbose_name='Лучший скор матчинга')),
                ('skipped', models.BooleanField(default=False, verbose_name='Пропущено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='supplier_feed.supplierfeed', verbose_name='Сессия')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Строка выгрузки',
                'verbose_name_plural': 'Строки выгрузок',
                'indexes': [models.Index(fields=['feed', 'product'], name='supplier_fe_feed_id_3ee31d_idx'), models.Index(fields=['feed', 'supplier_sku'], name='supplier_fe_feed_id_0e490d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(max_length=128, verbose_name='Артикул поставщика')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Связь поставщик — товар',
                'verbose_name_plural': 'Связи поставщик — товар',
                'unique_together': {('supplier', 'supplier_sku')},
            },
        ),
    ]
