# Generated by Django 5.2.5 on 2026-05-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_feed', '0002_supplierfeed_supplierfeedentry_supplierlink'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supplierfeedentry',
            new_name='supplier_fe_feed_id_3ee31d_idx',
            old_name='sf_entry_feed_product_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierfeedentry',
            new_name='supplier_fe_feed_id_0e490d_idx',
            old_name='sf_entry_feed_sku_idx',
        ),
    ]
