# Generated by Django 5.2.5 on 2026-05-31 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_nullable_supplierlink_product_and_feedmapping_columns'),
        ('supplier_feed', '0005_feedmapping_dataframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmapping',
            name='product_name_column',
            field=models.CharField(blank=True, max_length=128, verbose_name='Колонка названия товара'),
        ),
        migrations.AddField(
            model_name='feedmapping',
            name='product_sku_column',
            field=models.CharField(blank=True, max_length=128, verbose_name='Колонка артикула товара'),
        ),
        migrations.AlterField(
            model_name='supplierlink',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Товар'),
        ),
    ]
