# Generated by Django 5.2.5 on 2026-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_feed', '0006_nullable_supplierlink_product_and_feedmapping_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierfeedentry',
            name='best_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Лучший скор матчинга'),
        ),
    ]
