# Generated by Django 5.2.5 on 2026-06-06 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_feed', '0007_best_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedMarkupSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price_column', models.CharField(max_length=128, verbose_name='Колонка цены-источника')),
                ('output_column', models.CharField(max_length=128, verbose_name='Колонка расчётной цены')),
                ('feed_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markup_sets', to='supplier_feed.feedmapping', verbose_name='Конфигурация выгрузки')),
            ],
            options={
                'verbose_name': 'Набор наценок',
                'verbose_name_plural': 'Наборы наценок',
                'ordering': ['feed_mapping', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeedMarkupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Приоритет')),
                ('price_from', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Цена от')),
                ('price_to', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Цена до')),
                ('markup', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Наценка %')),
                ('increase', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Надбавка')),
                ('markup_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='supplier_feed.feedmarkupset', verbose_name='Набор наценок')),
            ],
            options={
                'verbose_name': 'Правило наценки',
                'verbose_name_plural': 'Правила наценок',
                'ordering': ['order'],
            },
        ),
    ]
