# Generated by Django 5.2.5 on 2026-06-12 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('supplier_feed', '0008_feedmarkupset_feedmarkuprule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedmarkupset',
            name='feed_mapping',
        ),
        migrations.CreateModel(
            name='FeedColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=128, verbose_name='Колонка')),
                ('role', models.CharField(choices=[('price', 'Цена'), ('stock', 'Остаток'), ('other', 'Другое')], max_length=16, verbose_name='Роль')),
                ('feed_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='supplier_feed.feedmapping', verbose_name='Конфигурация выгрузки')),
                ('price_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.pricetype', verbose_name='Тип цены')),
            ],
            options={
                'verbose_name': 'Маппинг колонки',
                'verbose_name_plural': 'Маппинги колонок',
            },
        ),
        migrations.DeleteModel(
            name='FeedMarkupRule',
        ),
        migrations.DeleteModel(
            name='FeedMarkupSet',
        ),
        migrations.AddConstraint(
            model_name='feedcolumnmapping',
            constraint=models.UniqueConstraint(fields=('feed_mapping', 'column_name'), name='supplier_feed_column_mapping_unique'),
        ),
    ]
