# Generated by Django 5.2.5 on 2026-06-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('supplier_feed', '0009_remove_feedmarkupset_feed_mapping_feedcolumnmapping_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedcolumnmapping',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'price'), _negated=True), ('price_type__isnull', False), _connector='OR'), name='supplier_feed_column_mapping_price_requires_type'),
        ),
    ]
