# Generated by Django 5.2.5 on 2026-07-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_productprice_sup_pt_idx'),
        ('supplier_feed', '0009_feedcolumnmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedmarkuprule',
            name='markup_set',
        ),
        migrations.RemoveField(
            model_name='feedmarkupset',
            name='feed_mapping',
        ),
        migrations.AddConstraint(
            model_name='feedcolumnmapping',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'price'), _negated=True), ('price_type__isnull', False), _connector='OR'), name='supplier_feed_column_mapping_price_requires_type'),
        ),
        migrations.DeleteModel(
            name='FeedMarkupRule',
        ),
        migrations.DeleteModel(
            name='FeedMarkupSet',
        ),
    ]
