# Generated by Django 5.2.5 on 2026-06-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_productprice_sup_pt_idx'),
        ('supplier_feed', '0012_product_trgm_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmapping',
            name='is_full_inventory',
            field=models.BooleanField(default=False, help_text='Выгрузки этого поставщика — полный снимок ассортимента. Остатки товаров, отсутствующих в фиде, обнуляются. См. ADR-0014.', verbose_name='Полная выгрузка остатков'),
        ),
    ]
