# Generated by Django 5.2.5 on 2026-04-29 06:55

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(unique=True, verbose_name='Название')),
                ('conf', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Настройка')),
                ('cols', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Столбцы')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dataframe/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'xlsm', 'csv'])], verbose_name='Файл')),
            ],
        ),
    ]
