# Generated by Django 5.2.5 on 2026-05-14 17:22

import dataframe.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('instructions', models.JSONField(blank=True, default=dataframe.models.default_instructions, verbose_name='Инструкции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dataframe',
                'verbose_name_plural': 'Dataframes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
