# Generated by Django 5.2.5 on 2026-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataframe',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataframe',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
