# Generated by Django 5.2.5 on 2026-05-02 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0002_dataframe_slug_alter_dataframe_name'),
        ('product', '0002_manufacturer_pricetype_stocktype_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataframe',
            name='cols',
        ),
        migrations.RemoveField(
            model_name='dataframe',
            name='conf',
        ),
        migrations.AddField(
            model_name='dataframe',
            name='create_new',
            field=models.BooleanField(default=False, verbose_name='Создавать если нет'),
        ),
        migrations.AddField(
            model_name='dataframe',
            name='index_row',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ряд для индексации'),
        ),
        migrations.AddField(
            model_name='dataframe',
            name='sheet_name',
            field=models.CharField(default='default', verbose_name='Название листа'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(null=True)),
                ('value', models.CharField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.contenttype', verbose_name='Контент')),
                ('dataframe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dataframe.dataframe')),
            ],
        ),
        migrations.CreateModel(
            name='DictItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(verbose_name='Если')),
                ('value', models.CharField(verbose_name='То')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dicts', to='dataframe.link', verbose_name='Столбец')),
            ],
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('dataframe', 'content'), name='contentitem'),
        ),
        migrations.AddConstraint(
            model_name='dictitem',
            constraint=models.UniqueConstraint(fields=('link', 'key', 'value'), name='linkdict'),
        ),
    ]
