# Generated by Django 5.2.5 on 2026-04-29 08:29

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0002_dataframe_slug_alter_dataframe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframe',
            name='conf',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Источник'),
        ),
    ]
