# Generated by Django 5.2.5 on 2026-04-30 06:08

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0003_alter_dataframe_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframe',
            name='cols',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Столбцы'),
        ),
    ]
