# Generated by Django 5.2.5 on 2026-05-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0004_dataframe_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataframe',
            name='create_new',
        ),
        migrations.RemoveField(
            model_name='dataframe',
            name='index_row',
        ),
        migrations.AlterField(
            model_name='dataframe',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dataframe',
            name='sheet_name',
            field=models.CharField(null=True, verbose_name='Название листа'),
        ),
    ]
