# Generated by Django 5.2.5 on 2026-05-06 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0005_remove_dataframe_create_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('measure', models.CharField(verbose_name='Еденица измерения')),
                ('contenttype', models.CharField(choices=[('str', 'Текст'), ('int', 'Целые числа'), ('float', 'числа с плавающей точкой'), ('Decimal', 'Десятичные числа')], verbose_name='Тип поля')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='link',
            name='contentitem',
        ),
        migrations.RemoveField(
            model_name='link',
            name='content',
        ),
        migrations.AlterField(
            model_name='link',
            name='dataframe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dataframe.dataframe'),
        ),
        migrations.AddField(
            model_name='link',
            name='contenttype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dataframe.contenttype', verbose_name='Контент'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(fields=('dataframe', 'contenttype'), name='contentitem'),
        ),
    ]
