# Generated by Django 5.2.5 on 2026-05-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0006_contenttype_remove_link_contentitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='value',
            field=models.CharField(null=True),
        ),
    ]
