# Generated by Django 5.2.5 on 2026-05-13 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0007_alter_link_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframe',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataframes', to='dataframe.filemodel', verbose_name='Файл'),
        ),
    ]
