# Generated by Django 5.2.5 on 2026-05-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0009_alter_link_value_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='initial',
            field=models.CharField(blank=True, null=True),
        ),
    ]
