# Generated by Django 5.2.5 on 2026-05-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0010_alter_link_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataframe',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
