# Generated by Django 5.2.5 on 2026-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataframe', '0011_alter_contenttype_slug_alter_dataframe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataframe',
            name='index_row',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Начальная строка'),
        ),
    ]
