# Generated by Django 5.2.5 on 2026-09-25 07:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0012_product_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('pim_field', models.CharField(blank=True, default='', help_text='Имя поля PriceManagerProduct в PIM, куда отправлять эту цену. Пусто — в PIM не отправляется. Поле должно быть заведено в PIM.', max_length=100, verbose_name='Поле в PIM')),
                ('show_on_page', models.BooleanField(default=True, verbose_name='Показывать на странице «Товары»')),
                ('sorting', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип цены товара',
                'verbose_name_plural': 'Типы цен товара',
                'ordering': ['sorting', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('source', models.CharField(choices=[('prime_cost', 'Себестоимость'), ('wholesale_price', 'Оптовая цена'), ('basic_price', 'Базовая цена'), ('m_price', 'Цена ИМ'), ('wholesale_price_extra', 'Оптовая цена доп.'), ('discount_price', 'Цена со скидкой'), ('kaspi_price', 'Цена Каспи'), ('fixed_price', 'Фиксированная цена')], default='prime_cost', max_length=32, verbose_name='От какой цены считать')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, help_text='Диапазон цены-источника, включительно.', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена от')),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена до')),
                ('date_from', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('markup', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(-100)], verbose_name='Наценка, %')),
                ('increase', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Надбавка, тг')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фиксированная цена, тг')),
                ('rounding', models.DecimalField(blank=True, decimal_places=2, help_text='Шаг округления вверх: 1, 10, 100… Пусто — без округления.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Округлять вверх до')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Меньше — важнее. Из нескольких подходящих правил одного типа цены действует одно.', verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('brands', models.ManyToManyField(blank=True, help_text='Пусто — все бренды, включая товары без бренда.', related_name='price_rules', to='product.brand', verbose_name='Бренды')),
                ('categories', models.ManyToManyField(blank=True, help_text='Вместе с подкатегориями. Пусто — все категории, включая товары без категории.', related_name='price_rules', to='product.category', verbose_name='Категории')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='product_pricing.productpricetype', verbose_name='Какую цену считать')),
            ],
            options={
                'verbose_name': 'Наценка на товар',
                'verbose_name_plural': 'Наценки на товар',
                'ordering': ['price_type__sorting', 'price_type__name', 'priority', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('source_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Цена-источник')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Рассчитана')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product', verbose_name='Товар')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='product_pricing.productpricerule', verbose_name='Наценка')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product_pricing.productpricetype', verbose_name='Тип цены')),
            ],
            options={
                'verbose_name': 'Расчётная цена товара',
                'verbose_name_plural': 'Расчётные цены товаров',
                'constraints': [models.UniqueConstraint(fields=('product', 'price_type'), name='product_price_product_type_uniq')],
            },
        ),
    ]
