# Generated by Django 5.2.5 on 2026-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricerule',
            name='only_sets',
            field=models.BooleanField(default=False, help_text='Только товары с составом набора из PIM (product.ProductSetItem).', verbose_name='Только наборы'),
        ),
        migrations.AlterField(
            model_name='productpricerule',
            name='source',
            field=models.CharField(choices=[('Главный прайс (ГП)', [('prime_cost', 'Себестоимость'), ('wholesale_price', 'Оптовая цена'), ('wholesale_price_extra', 'Оптовая цена доп.'), ('basic_price', 'Базовая цена'), ('m_price', 'Цена ИМ'), ('kaspi_price', 'Цена Каспи'), ('discount_price', 'Цена со скидкой')]), ('Прайс поставщика (ПП), в тенге', [('supplier_price', 'Цена поставщика'), ('rrp', 'РРЦ'), ('supplier_discount_price', 'Цена поставщика со скидкой')]), ('Без источника', [('fixed_price', 'Фиксированная цена')])], default='prime_cost', max_length=32, verbose_name='От какой цены считать'),
        ),
    ]
