# Generated by Django 5.2.5 on 2026-09-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_supplier_prices'),
        ('product_pricing', '0002_rule_only_sets_pp_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricerule',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Только эти товары. Пусто — любые.', related_name='price_rules', to='product.product', verbose_name='Товары'),
        ),
    ]
