# Generated by Django 5.2.5 on 2026-06-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_feed', '0007_best_score'),
        ('transform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='Приоритет')),
                ('condition', models.JSONField(blank=True, null=True, verbose_name='Условие')),
                ('formula', models.JSONField(verbose_name='Формула')),
                ('feed_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transform_rules', to='supplier_feed.feedmapping', verbose_name='Конфигурация выгрузки')),
                ('target_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transform_rules', to='transform.snapshotfield', verbose_name='Целевое поле')),
            ],
            options={
                'verbose_name': 'Правило трансформации',
                'verbose_name_plural': 'Правила трансформации',
                'ordering': ['feed_mapping', 'priority'],
            },
        ),
    ]
