# Generated by Django 5.2.5 on 2026-06-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_importjob_target'),
        ('supplier', '0001_initial'),
        ('supplier_feed', '0007_best_score'),
        ('transform', '0002_transformrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Данные снимка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='product.product', verbose_name='Товар')),
                ('source_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='supplier_feed.supplierfeed', verbose_name='Источник выгрузки')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='supplier.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Снимок товара',
                'verbose_name_plural': 'Снимки товаров',
                'ordering': ['product', 'supplier'],
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
